### ISSUE TITLE
IE Plugin crash

### ISSUE THREAD

**Issue by jauhenk** [Temasys/AdapterJS#116]
Hey!
1. Disable all recording devices in the sound settings.
2. Call getUserMedia
3. Dropdown for microphone selection is empty.
4. Press OK
5. Plugin crashes.

**Comment by johache** [comment]
Hi,
Issue reproduced, it's the same when no video devices are enabled.
I'll look into it, thanks for the heads up!

**Comment by johache** [comment]
Hi Eugene,
FYI, the issue is fixed internally it will be a included in the next plugin release, probably 2 weeks from now.
Thanks again for the bug report ;)
