### ISSUE TITLE
Keeping up with WebRTC spec in plugin?

### ISSUE THREAD

**Issue by z0r1k** [Temasys/AdapterJS#121]
Hi all,

in Chrome 46 Google implemented some changes to SDP codec line as well as navigator.mediaDevices() which includes promise based getUserMedia, enumerateDevices for both input and output.

Also stream.label will be deprecated and to stop stream and get rid of camera indicator you need to call stop on MediaStreamTrack and not on stream itself.

Is there any plan for temasys to keep up with these changes and what is the state of w3c webrtc spec compliance?

**Comment by z0r1k** [comment]
Related to https://github.com/Temasys/AdapterJS/issues/95

**Comment by z0r1k** [comment]
And one more https://github.com/Temasys/AdapterJS/issues/127

**Comment by johache** [comment]
MST::stop released in 0.8.862.
stream.id released as well, although I'm not sure when.
AJS adds support for navigator.mediaDevices since 0.13.0.

Closing this issue.
