### ISSUE TITLE
Add support for MediaStreamTrack.stop()

### ISSUE THREAD

**Issue by z0r1k** [Temasys/AdapterJS#127]
Hi,

it looks like in latest plugin version ```stream.getTracks()``` support was added, but returned tracks doesn't have ```stop``` method. 
In fact it doesn't really look like that it has any of methods described by spec. 

Could you, please, start to fully support MediaStreamTrack spec?

Thank you in advance.

**Comment by johache** [comment]
Yep, that is a known limitation of the plugin.
Adding MST.stop brings a lot of instability in the plugin, so we kept this feature disabled so far.
As the spec and Chrome are moving toward more focus on `MediaStreamTrack`, we will try to re-eneable those

**Comment by johache** [comment]
Fixed from 0.8.862, released on 19 Nov, 2015.
Closing this issue.
