### ISSUE TITLE
Support enumerateDevices

### ISSUE THREAD

**Issue by grydstedt** [Temasys/AdapterJS#136]
Any timeline on adding support for `enumerateDevices`?

**Comment by johache** [comment]
Hi,

This branch has a beta support for enumerateDevices:
https://github.com/Temasys/AdapterJS/tree/TWP-287-as-a-plugin-user-i-want-to-have-

A few notes: 
* there should be a release release, this should not be part of it
* enumerateDevices is promise based, and therefore, it will not work on browser sur as IE which don't have such support. We are looking into possible dependencies too add promise support, but haven't made a choice yet.
* this is a dev branch, not everything will work 100%. You will have to run npm install and grunt publish and take the result from the publish folder.

**Comment by johache** [comment]
Hi, I think this issue was resolved a while ago (0.13.0 ??)
I'm closing it.

**Comment by frutality** [comment]
Hi, is this feature working?
I'm having some problems which I described here: https://groups.google.com/forum/#!topic/meetecho-janus/EUbalHmht-w

Any advice would be great.

**Comment by johache** [comment]
Hi,
It does.
You can see a demo here : 
https://plugin.temasys.com.sg/demo/src/content/peerconnection/munge-sdp/

note that there might be some integration to be done on the side of janus.js, I don't really know about that...

Hope this helps.
