### ISSUE TITLE
getUserMedia require https:// on localhost.

### ISSUE THREAD

**Issue by Goatic** [Temasys/AdapterJS#142]
for some reason I'm getting this error. I've tested Chromes own webkitgetUserMedia, which works fine. This, however doesn't.

**Comment by johache** [comment]
Hi,

Which browser are you getting this error on ?

**Comment by Goatic** [comment]
Chrome

**Comment by johache** [comment]
Ok, I'm a little confused by what you're telling me.
- Chrome does require https for getUserMedia (from M46 I think) on all urls. See Google's announcement : https://www.youtube.com/watch?v=HCE3S1E5UwY 
- However, I believe there is an exception on localhost (at least I can gUM on non-https localhost)

So the error you are talking about would be expected on all addresses but localhost.

**Comment by Goatic** [comment]
I have a project using Chrome's native API for gMU, which works great on localhost without ssl. When I try to use Skylink.js for the same purpose, I get an error, stating that I need to run my application with ssl encryption.

I've contacted Skylink support with a ticket, and they've processed my issue - I will close this one up :)
