### ISSUE TITLE
"Automation server can't create object"

### ISSUE THREAD

**Issue by Lenne231** [Temasys/AdapterJS#143]
Hello,

i'm trying to use the plugin on two different systems in IE. All ActiveX policies are the same now and it works on one system, on the other system if i call `new ActiveXObject('Tem.TemWebRTCPlugin')` it always throws the error "Automation server can't create object". Other plugins work i.e. `new ActiveXObject('ShockwaveFlash.ShockwaveFlash')`.

The only difference i can see right now is if i go to "Manage add-ons" the publisher of the plugin is "Not Available", on the other system it is "(Not verified) Temasys"

**Comment by johache** [comment]
Are you using the same version of the plugin on both systems ?
If yes are you using 0.8.863 ? 
Can you try uninstalling the plugin and re-installing it ?
I've never seen this issue so far...

**Comment by Lenne231** [comment]
The problem was that the plugin was installed in a system directory and not in the user directory.

**Comment by johache** [comment]
Hum, that's unexpected. Did you use the standard Temasys installer the first time ?
Any idea why it was installed there ?
