### ISSUE TITLE
How to alter this code...?

### ISSUE THREAD

**Issue by transonly** [Temasys/AdapterJS#144]
Could you please take a look at my question?

http://stackoverflow.com/questions/34659427/temasys-howto-alter-existing-code

Or will it be left unanswered like most of the question about Temasys on stack?

**Comment by johache** [comment]
Hi,

I just answered your question on stackoverflow.

For future questions, I strongly suggest you ask them on our numerous customer facing portals:
* Global support: http://support.temasys.com.sg/support/home
* Plugin mailing list: https://groups.google.com/forum/#!forum/temasys-discuss-webrtcplugin
* AdapterJS tickets on GitHub : https://github.com/Temasys/AdapterJS/issues

We use those to help centralize and track issues. You would get an answer much faster on those.

Thanks and regards,
J-O
