### ISSUE TITLE
Firefox 43 - not working due to deprecations.

### ISSUE THREAD

**Issue by igorpavlov** [Temasys/AdapterJS#148]
This adaptor **doesn't work in FF43**, Mac OS 10.11. There are 2 major changes FF did (those are extracts from console.log):

1. RTCIceServer.url is deprecated! Use urls instead.
2. Mandatory/optional in createOffer options no longer works! Use {"offerToReceiveAudio":true,"offerToReceiveVideo":true,"mozDontOfferDataChannel":true} instead (note the case difference)!

I think I understand both. 

1. Allows to specify several URLs in ICE credentials, which probably means a transformation of {url:"url"} to {urls:["url"]}. 
2. Transforms constraints {mandatory: {offerToReceiveAudio:true}} to simply {offerToReceiveAudio:true}. 

I think webrtc/adaptor already supports it, shouldn't this adaptor support it ASAP as well?

**Comment by johache** [comment]
Hi Pavlov,

In all this, I am assuming you are referring to 
this test : https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
against this test : https://plugin.temasys.com.sg/demo/samples/web/content/peerconnection/trickle-ice/index.html
Is that correct ?

1. Our sample is using AJS function createIceServer, which is actually deprecated.
You are right however. The format will fail on FF43+, and we will correct it.

2. This is really dependent on the sample. AJS has nothing to do with the constraint format. 
You can correct your own application as you feel relevant.

I hope this helps,
J-O

**Comment by igorpavlov** [comment]
Will the deprecated function be fixed in AdapterJS lib? If yes, when?

Igor Pavlov. Via toaster.

**Comment by johache** [comment]
createIceServer should be fixed in AJS, yes.
I don't have an exact ETA to give you, but probably within 2 weeks

**Comment by johache** [comment]
Hi, created a PR here : https://github.com/Temasys/AdapterJS/pull/157
Should be a part of the next release.
This is only for the url(s) part.


Note that the support for the new offer options in the plugin should also arrive in the next release (0.8.867).

**Comment by johache** [comment]
PR merged and released: 
https://github.com/Temasys/AdapterJS/releases/tag/0.13.1

I am closing this issue, please feel free to re-open it if relevant.
