### ISSUE TITLE
Doesn't set webrtcDetectedType for Firefox or Chrome

### ISSUE THREAD

**Issue by lcamacho** [Temasys/AdapterJS#152]
I checked the adapter and only sets webrtcDetectedType for plugin.

**Comment by johache** [comment]
Hi,

You seem to be right on this. It should not be hard to fix, I'll try to do that today.
In the mean time, you should be able to use `webrtcDetectedBrowser` to identify which browser you are on.

Thanks,
J-O

**Comment by johache** [comment]
Hi, PR for your issue here : https://github.com/Temasys/AdapterJS/pull/156
Waiting on validation.

**Comment by johache** [comment]
PR merged, closing the issue ;)
