### ISSUE TITLE
attachMediaStream_base is not a function in Chrome 48

### ISSUE THREAD

**Issue by rusekr** [Temasys/AdapterJS#154]
Hello! Updated AdapterJS to 0.13 because 0.12.1 showed mime type errors in IE11 on attaching media to video element (with new version of plugin (0.8.866).

Now in IE11 all works well bug Chrome 48 have following error:

    TypeError: attachMediaStream_base is not a function at attachMediaStream (https://osdp-sandbox.teligent.ru/iccw/libraries/adapter.debug.js:692:5)

What can it be? 
Thanks!

**Comment by johache** [comment]
Hi,
I've just tested on Chrome 49 and don't have this issue.
https://plugin.temasys.com.sg/demo/samples/web/content/peerconnection/states/index.html

Do you have a live version of your app on which we could reproduce ?

**Comment by rusekr** [comment]
mmmm, tested with CDN link instead of built from master branch - all work.
Compared built with "grunt publish" and CDN versions. Seems built with that command version don`t includes google`s adapterjs. Nothing is inserted between these lines:

      // INJECTION OF GOOGLE'S ADAPTER.JS CONTENT

      // END OF INJECTION OF GOOGLE'S ADAPTER.JS CONTENT

**Comment by johache** [comment]
oh, so this issue is probably a missing submodule. You can run
``` 
git submodule init
git submodule update
npm install
grunt publish
```

**Comment by rusekr** [comment]
Thanks for pointing this! Forgot to read updated README

Closing issue now
