### ISSUE TITLE
Use local variables within a scope

### ISSUE THREAD

**Issue by ibc** [Temasys/AdapterJS#155]
There is no reason at all to set all the variables and functions within a `AdapterJS` object. For example, this looks a bit ugly:

```js
AdapterJS.maybeThroughWebRTCReady = function() {
   [...]
};
```

It seems that `AdapterJS` is used as a "container" of everything just to not declare global variables and functions in the `window` namespace.

There are tons of ways to handle this better, and the easiest one is to define a closed scope, declare common local variables and functions in there, and return the desired exported object. For example, using an auto-executable function:

```js
var AdapterJS = (function() {
  // All the stuff here is private
  var exported = {};
  var foo = 123;
  var bar = 456;

  function lalala() {
    // lalala
  }

  exported.lalala = lalala;
  exported.data = { foo: foo, bar: bar };

  return exported;
})();
```

And better than that, I would recommend using `browserify` so this JS library does not pollute `window` with a global `AdapterJS` object when CommonJS is used (`var adapter = require('adapter.js');'`) and, at the same time, the library would export `window.AdapterJS` if no modern JS loader is detected in the website.

**Comment by ibc** [comment]
More: 

Why is this needed?:

```js
AdapterJS.WebRTCPlugin.documentReadyInterval = setInterval(function () {
      if (document.readyState === 'complete') {
        // TODO: update comments, we wait for the document to be ready
        clearInterval(AdapterJS.WebRTCPlugin.documentReadyInterval);
        AdapterJS.WebRTCPlugin.pluginState = AdapterJS.WebRTCPlugin.PLUGIN_STATES.READY;

        AdapterJS.maybeThroughWebRTCReady();
      }
}, 100);
```

It does not require storing the timer in the ÀdapterJS` object:

```js
var timer = setInterval(function () {
      if (document.readyState === 'complete') {
        // TODO: update comments, we wait for the document to be ready
        clearInterval(timer);
        AdapterJS.WebRTCPlugin.pluginState = AdapterJS.WebRTCPlugin.PLUGIN_STATES.READY;

        AdapterJS.maybeThroughWebRTCReady();
      }
}, 100);
```

And even better, by using [domready](https://www.npmjs.com/package/domready):

```js
// Node+Browserify way:
var domready = require('domready');

window.__TemWebRTCReady0 = function() {
	debug('__onTemasysPluginReady()');

	domready(function() {
		AdapterJS.WebRTCPlugin.pluginState = AdapterJS.WebRTCPlugin.PLUGIN_STATES.READY;

        AdapterJS.maybeThroughWebRTCReady();
	});
};
```

In fact, the plugin gets ready when the DOM is ready. There is no need to handle a parallel and equivalent state machine.

**Comment by johache** [comment]
Hi,

While I agree with most of what you are suggesting, and we would like to see it happen in future iterations, that doesn't sound like a functional issue for us. Thus we will keep it in mind for future iterations, but won't allocate resources for it now.
That being said, we always welcome pull requests :)

The timer part is a 2 liner, I'll push something in a minute.

Side note: AJS is used as a container for a few variables, but it also places others in the global scope (RTCPC, gUM, attachMediaStream, ...)
Side note 2: to keep AJS as a replace drop-in to adapter.js by Google, we don't want to have any dependency on other JS modules.

**Comment by ibc** [comment]
Fair. Let's close this issue.
