### ISSUE TITLE
grunt jshint errors out

### ISSUE THREAD

**Issue by zirho** [Temasys/AdapterJS#161]
I freshly cloned repo and did what is in instruction in README 
and got this

`Running "jshint:build" (jshint) task

    124 |              if (filePath.indexOf(grunt.config.get('googleAdapterPath')) != -1) {
                                                                                     ^ Expected '!==' and instead saw '!='.

>> 1 error in 2 files
Warning: Task "jshint:build" failed. Use --force to continue.

Aborted due to warnings.
AdapterJS (master) $`

**Comment by johache** [comment]
Hi, good catch,  thanks for the feedback.
Fixed it here with a bunch of other issues : https://github.com/Temasys/AdapterJS/pull/162
Wait for the PR to be validated :)

Meanwhile, you can still run `grunt publish` to generate your AJS. `grunt jshint` just checks the js for typos, and style.

**Comment by zirho** [comment]
Hi, no problem.
I appreciated quick response.

**Comment by johache** [comment]
PR merged and released: 
https://github.com/Temasys/AdapterJS/releases/tag/0.13.1

I am closing this issue, please feel free to re-open it if relevant.
