### ISSUE TITLE
Safari iframe - access dialog box not appearing

### ISSUE THREAD

**Issue by igorpavlov** [Temasys/AdapterJS#164]
Safari 9.0, MacOS 10.11

I have an origin page (https) and an iframe on this page (also https). Domains are different though. The camera/mic access box doesn't appear. If I open the URL used in iframe directly in the Safari tab - the dialog box appears.

**Comment by johache** [comment]
Hi,
We have an example here of an functioning iframe : 
https://plugin.temasys.com.sg/demo/samples/web/content/getusermedia/iframe/index.html

Can you check if it works on your machine ?
Both urls are on the same domain in our case. I don;t think that is should change anything though.

Is you app live, can we have access to it ?

**Comment by igorpavlov** [comment]
Yep, here is a JS fiddle - it generates iframe and loads URL. https://jsfiddle.net/igorpavlov/Lbdzub6h/3/

**Comment by johache** [comment]
I get the following errors on Safari: 
[Error] Error while parsing the 'sandbox' attribute: 'allow-modals' is an invalid sandbox flag. (3, line 546)
[Error] Failed to load resource: too many HTTP redirects (jh4yi8gq7xh3pu0a, line 0)

Does not seem to be webrtc related.

**Comment by igorpavlov** [comment]
You are absolutely right, this was due to JSfiddle. Closing this one.
