### ISSUE TITLE
getStats support?

### ISSUE THREAD

**Issue by igorpavlov** [Temasys/AdapterJS#167]
Safari and IE. Is it already implemented (couldn't find in the documentation)? If not - this is an important piece as there is no way to track peer connection status then.

**Comment by johache** [comment]
PeerConnection.getStats is implemented.
Please find the spec here : https://www.w3.org/TR/webrtc/#widl-RTCPeerConnection-getStats-void-MediaStreamTrack-selector-RTCStatsCallback-successCallback-RTCPeerConnectionErrorCallback-failureCallback
