### ISSUE TITLE
Safari. Cannot retreive <object> element from DOM

### ISSUE THREAD

**Issue by igorpavlov** [Temasys/AdapterJS#176]
I am reopening this ticket https://github.com/Temasys/AdapterJS/issues/158 with a better explanation. Using Safari 9.0.3 on Mac OS 10.11.3.

I have this object in DOM. This object is created within AdapterJS via attachMediaStream (replicated from `<video id="remoteVideo_1">` object).

```
<object id="remoteVideo_1" class="remoteVideo" type="application/x-temwebrtcplugin" width="443" height="332">
    <param name="pluginId" value="remoteVideo_1"/>
    <param name="pageId" value="x7yo9uqrfsa"/>  
    <param name="windowless" value="true"/>
    <param name="streamId" value="27"/>
    <param name="tag" value="video"/> 
</object>
```

But when I execute something like document.getElementById("remoteVideo_1") in the console it throws the following error:

**`"TypeError: undefined is not an object (evaluating 'node.getAttribute(\"class\").trim')" = $1`**

**If I modify attribute "type" of the `<object>` OR remove "class" attribute, the error disappears:**

`<object id="remoteVideo_1" class="remoteVideo" type="application/x-temwebrtcplugin-test" width="443" height="332">...</object>`

`document.getElementById("remoteVideo_1") // executing in console returns:`

```
<object id=​"remoteVideo_1" class=​"remoteVideo hidden" type=​"application/​x-temwebrtcplugin-test" width=​"443" height=​"332">​…​</object>​
 = $1
```

What am I doing wrong? Can provide more info if needed.

**Comment by johache** [comment]
Hi,

I have reproduced the issue.
A few points:

- this issue is Safari only
- it seems like Safari cannot read the plugin class attribute (from the DOM)
- it doesn't prevent the plugin from working. You can still call `document.getElementById("remoteVideo_1").getUserMedia`. 
The issue is only about console display and access to the class attribute

We'll be looking into this issue, thanks

**Comment by johache** [comment]
Additional point, the issue seems to happen only on Safari 9

**Comment by igorpavlov** [comment]
Thank you for the investigation. True, it doesn't look like it terminate the script, however, it now can be referred to the original ticket #158:

```
var elem = document.getElementById("remoteVideo_1");
attachMediaStream(elem,stream); // this will not be executed, but will throw an error.

```
Error:
`TypeError: element.setStreamId is not a function. (In 'element.setStreamId(streamId)', 'element.setStreamId' is undefined)`

And it looks like it is happening exactly because the element could not be retrieved from DOM

**Comment by johache** [comment]
Hum, again, while I get the same JS error printed as before:
``` "TypeError: undefined is not an object (evaluating 'node.getAttribute(\"class\").trim')" = $1```

My code seems to run fine. 
It still looks like Safari is unable to print the <object> element.

You can try it out on this page : https://plugin.temasys.com.sg/demo/src/content/getusermedia/gum/
