### ISSUE TITLE
dataChannel.addEventListener('open', ...) not working

### ISSUE THREAD

**Issue by Rugvip** [Temasys/AdapterJS#183]
I'm testing in Safari using the plugin, and addEventListener works for most classes, but it doesn't seem to work for DataChannels.

If not implemented in the plugin, this seems like something that could be added in the JS layer instead.

`dataChannel.onopen = ...` is working as intended.

**Comment by johache** [comment]
Excellent point, thanks for bringing it up.
I fixed it locally, there seems to be the same issue for MediaStream.onended, we'll fix that too.

That should be in the next release.
