### ISSUE TITLE
End of candidates in Microsoft Edge

### ISSUE THREAD

**Issue by roma-lukashik** [Temasys/AdapterJS#189]
Hi,

How to wait until the end of candidates is fired in Microsoft Edge? Usually "onicecandidate" event returns NULL entry for the latest "event.candidate" object. But in Microsoft Edge I receive an empty object after each ice candidate and cannot check "!event.candidate".

Thanks in advance.

**Comment by letchoo** [comment]
Hi @roma-lukashik,
- on Chrome you receive null candidates that you would usually just ignore
- on Egde, this is replaced by an EndOfCandidate

You cannot send the EndOfCandidate to Chrome/FF/Plugin, as it is not a valid candidate.
However, on Edge, you do need to add one.

So you will have to adapt to the type of peer on the remote side and drop/create candidates accordingly
