### ISSUE TITLE
navigator.mozGetUserMedia has been replaced by navigator.mediaDevices.getUserMedia

### ISSUE THREAD

**Issue by transonly** [Temasys/AdapterJS#196]
Shouldn't this be updated in the adapter.debug.js?

**Comment by johache** [comment]
Hi,
As far as I can tell, webrtc-adapter (our main dependency) is still relying on mozGetUserMedia.
As long as it is the case, there is not much to gain by us doing the changes.

Note however, that mozGetUserMedia is only deprecated for now, you can still use it for a couple of version.
We will definitely enforce the changes by then.

Thanks

**Comment by transonly** [comment]
Ok,

Thanks for answering.
