### ISSUE TITLE
Updating media streams doesn't work in Safari

### ISSUE THREAD

**Issue by Rugvip** [Temasys/AdapterJS#205]
This simple test case seems broken:

```
navigator.getUserMedia({video: true}, function (stream) {
    AdapterJS.attachMediaStream(videoElement, null)
    AdapterJS.attachMediaStream(videoElement, stream)
}, function (error) {
    console.error(error)
})
```

While directly assigning the stream without first assigning null works just fine.

It looks like the streamId of the object tag isn't updated.

**Comment by Rugvip** [comment]
A workaround for this seems to be to never assign a null stream first. If that's avoided it's fine to assign a null stream and then back to a stream later.

**Comment by johache** [comment]
Hi, I have reproduced the issue and started fixing it.
I'll keep you posted when it's ready to be shipped.
