### ISSUE TITLE
SimpleWebRTC and Temasys' IE/Safari plugin (+ its adapted version of adapter.js)

### ISSUE THREAD

**Issue by DanyPell** [Temasys/AdapterJS#206]
Hi,

I've been building my app with SimpleWebRTC, and I am pretty deep in development, too deep to simply stop using it.

And I really want to use Temasys' webRTC plugin (and its version of adapter.js) to support Safari and IE.

I tried setting it up today, but I get errors (I'm testing in Safari only for now).

One error I am getting is 
TypeError: this.peerconnection.getLocalStreams.bind is not a function. (In 'this.peerconnection.getLocalStreams.bind(this.peerconnection)', 'this.peerconnection.getLocalStreams.bind' is undefined)
TraceablePeerConnection — simple-webrtc.js:10682

The other is that the local stream is simply not going into the video element.

I am pretty sure there would be other errors besides these ones above, so optimally I am looking for someone who've successfully used SimpleWebRTC (they have a demo app on their github page which takes a minute to setup locally...) and Temasys' webRTC Plugin together.

Looking forward to the discussion…

Thanks
Dany

**Comment by johache** [comment]
Hi,
All the webrtc elements/function are defined by the plugin and thus plugin element. They have limited APIs. In your case, bind is not defined. You will have to find another way of implementing your app.

The same way, the stream cannot be renderer in a <video> element. We replace them with <object> (plugin) elements. AdapterJS does that for you with attachMediaStream.

We used to have a version of AppRTC integrated with the plugin but discontinued it. You can however have a look at our code samples that should give you a good idea of how to manage the plugin integration: https://plugin.temasys.com.sg/demo/

Finally, a document is available and gives a list of todos to integrate the plugin with your webapp : http://confluence.temasys.com.sg/display/TWPP/How+to+integrate+the+Temasys+WebRTC+Plugin+into+your+website

I hope this help,
J-O

**Comment by johache** [comment]
Closing the ticket, reopen if needed

**Comment by ee11131** [comment]
So what you're saying is that at the moment temasys plugin cannot be used with SimpleWebRTC because it uses bind? Even with Add bind() polyfill to plugin functions #291?

**Comment by johache** [comment]
Hi,
Currently, AJS does NOT support bind on plugin objects. Therefore, SimpleWebRTC could not be used if it requires bind(), no.
We will come back to #291 , but right now we are on a different sprint.
We'll probably come back to that question early December.
