### ISSUE TITLE
IE 11 AdapterJS.webRTCReady wont trigger

### ISSUE THREAD

**Issue by catin-black** [Temasys/AdapterJS#209]
I have a problem with trigger AdapterJS.webRTCReady on IE11.

````
$.getScript('//cdn.temasys.com.sg/skylink/skylinkjs/0.6.x/skylink.complete.min.js', function(data, textStatus, jqxhr) {
    if (jqxhr.status == 200) {
        AdapterJS.webRTCReady(function (isUsingPlugin) {
             //body
        }
}
````

AdapterJS.webRTCReady works on other browsers without any problem, but on IE(11) nothing happend.

**Comment by johache** [comment]
Hum, it all looks good to me.
Was you IE restarted after installing the plugin ?
Con you check that the jqxhr.status == 200 condition passes ?

**Comment by catin-black** [comment]
I use clear version without plugin - It is becouse of that? How can I check without plugin?
yes - jqxhr.status == 200

**Comment by johache** [comment]
Hey, just picking up on this : 
If you have no plugin installed, webrtcReady will never be triggered, since your webrtc APIs are never made available...

Install the Temasys webrtc plugin, restart IE and you should be fine.

I'm closing this ticket, please re-open if you need to.
