### ISSUE TITLE
Change Scaling of Video in Object

### ISSUE THREAD

**Issue by dmurtari** [Temasys/AdapterJS#210]
I'm having an issue with getting the `object` inserted by AdapterJS to behave the same as a `video` tag. 

Our current usage of video is such that we would like the video to always fill the parent container while maintaining aspect ratio. We've achieved this in Chrome and Firefox, but are struggling to get the same affect in IE and Safari where Temasys is used. The `object` respects the CSS and fills the parent, but the video inside the `object` always maintains aspect ratio to fit within the `object`, instead of filling the `object` with no border as we would like.

I've confirmed that the same styles are being applied to both the `video` tags in Chrome/Firefox and the `object` tags in IE/Safari. Is there a way to change how the plugin scales the video within the `object` tag?

**Comment by johache** [comment]
Hi,
So just to be clear, what you wants is to take as much space as possible, which will basically lead to cropping some of the image.

This is currently not supported. As you said, the plugin will render with the original ratio, taking as much space as possible WITHIN the object.

As a work around, you can try to make a bigger video, and place it under a mask ?

**Comment by dmurtari** [comment]
Yes that is correct -- I'm trying to have the video take up as much space as possible, keeping the original aspect ratio but cropping the video if necessary. 

Thanks for the confirmation, I wanted to make sure I wasn't missing anything obvious. I'll go with the workaround for now.
