### ISSUE TITLE
MS Edge support?

### ISSUE THREAD

**Issue by igorpavlov** [Temasys/AdapterJS#213]
Any roadmap on MS Edge Support?

**Comment by johache** [comment]
Hi,

If you check this branch, you'll see that we started working on updating AJS dependency to the webtc-adapter repo:
https://github.com/Temasys/AdapterJS/tree/AJS-269-webrtc-adapter-update
This should bring significant improvement to the Edge support.

Unfortunately it seems like the update broke our test system (I think it comes from the browserify system in webrtc-adapter).
Hopefully, I can work this out in the next 10 days.

If you want to have a look on your own, or provide any feedback regarding the issue, you are welcome to do so.

Cheers,
J-O

**Comment by igorpavlov** [comment]
Sounds good! How can I compile a build on my own from this branch https://github.com/Temasys/AdapterJS/tree/AJS-269-webrtc-adapter-update?

**Comment by igorpavlov** [comment]
I compiled the adapter with grunt and it seems that the createIceServer() function does not exists in Edge. Is this expected?

**Comment by johache** [comment]
Hi,

``createIceServer`` and ``createIceServers`` are indeed missing.
As I said last time, this is a WIP.

Each browser gets its own implementation of those function, so we need to re-implement it for Edge (should not be super complicated)

**Comment by igorpavlov** [comment]
Hi @johache ! Is there any news on the update, we are looking forward to it soooo much! :) Any info on the status will be very very appreciated!

**Comment by igorpavlov** [comment]
Hello! Are there any updates on the status?

**Comment by johache** [comment]
Hi,
A couple of issues : 
- work on this is blocked by this PR on our end: https://github.com/Temasys/AdapterJS/pull/216#issuecomment-241311005

- We are under some constrains at the moment and probably won't get much work on your issue done for the next couple weeks.

If you have the time, feel free to make a PR into AJS-269-webrtc-adapter-update-v2.0.2.
My guess is that the code should mainly be copied from the Chrome and FF implementation.

Sorry for the delay...

**Comment by johache** [comment]
FYI, a big merge was just done in AJS, and it should lead to a greater support for Edge.
You can already access it on our dev branch, and it will probably be released next week.

**Comment by igorpavlov** [comment]
Great news! Thank you very much for the update.

**Comment by transonly** [comment]
Trying to find this dev branch. :-) Where is it?

**Comment by johache** [comment]
https://github.com/Temasys/AdapterJS/tree/development.
You will need to build using npm and grunt.

**Comment by johache** [comment]
Hi all,
There was a big Edge support release today (0.14.0).

I'll close this issue.
Cheers

**Comment by igorpavlov** [comment]
Hey! Fantastic news.

Just tried to test 0.14.0, but it still says createIceServer is null.

I am using this file https://github.com/Temasys/AdapterJS/blob/master/publish/adapter.min.js

Am I doing something wrong?

**Comment by johache** [comment]
No, that is expected.
CreateIceServer was removed from webrtc-adapter.
We copied the old implementation for Chrome, FF, and Safari (so that existing implementations would not break), but did not add an implementation for Edge yet.

**Comment by igorpavlov** [comment]
Thank you. I am now getting an error here (Chrome, FF, Safari, Opera work fine):

SCRIPT5007: Object expected
adapter.js (837,8)

adapter.js - https://gist.github.com/igorpavlov/4caaa8243e8ec6d6622bb52dde1b7a7d 

I tried to understand what actually happens - but no luck. Any ideas?
