### ISSUE TITLE
Recommended way to mute video audio?

### ISSUE THREAD

**Issue by dmurtari** [Temasys/AdapterJS#215]
We're looking for a way to receive video without playing back audio from the video. From the documentation, as well as issue #34, it looks like `<video muted></video>` is not supported by the plugin. The workaround that we found is to disable audio using `getAudioTracks()[0].enabled = false`. Is this the current recommended way to mute audio from video?

**Comment by johache** [comment]
You can either use ``getAudioTracks()[0].enabled = false``, or you can use ``videoPlayer.muted = true`` once the <video> element is replaced by an <object> (that is after you call ``attachMediaStream``)

Note that they do different things. Muted will only mute this specific renderer, but setting enable = false will prevent this steam from being played anywhere, and even from being sent to a different peer.

**Comment by dmurtari** [comment]
Great, thank you for the recommendations
