### ISSUE TITLE
window.propName global variable

### ISSUE THREAD

**Issue by ibc** [Temasys/AdapterJS#222]
Here a global variable is being created:

https://github.com/Temasys/AdapterJS/blob/master/source/adapter.js#L1325

**Comment by ibc** [comment]
Also `properties` in https://github.com/Temasys/AdapterJS/blob/master/source/adapter.js#L1322

**Comment by johache** [comment]
yep, easy PR : https://github.com/Temasys/AdapterJS/pull/224.
thx.
