### ISSUE TITLE
Screen sharing plugin prompt stopped working in 0.14

### ISSUE THREAD

**Issue by zdila** [Temasys/AdapterJS#228]
Problem is at https://github.com/Temasys/AdapterJS/blob/0.14.0/source/adapter.screenshare.js#L54 because now `error.name` will contain 'NotAllowed'.

**Comment by johache** [comment]
Yep, reproduced, should be fairly easy to fix.
@letchoo, @ncurrier, FYI.

**Comment by johache** [comment]
https://github.com/Temasys/AdapterJS/pull/231

**Comment by johache** [comment]
PR merged, thx :)
