### ISSUE TITLE
Safari Plugin doesn't work with Sierra

### ISSUE THREAD

**Issue by igorpavlov** [Temasys/AdapterJS#236]
It worked in Safari 9, now it just doesn't want to fire up on getUserMedia()

**Comment by johache** [comment]
Hi,

Are you using an up to date version of AJS ?

The plugin detection system was updated in 0.13.4 and is needed for AJS to detect and inject the plugin element.

See https://github.com/Temasys/AdapterJS/releases

**Comment by igorpavlov** [comment]
Hi,

I am using 0.14.0

**Comment by igorpavlov** [comment]
Yes, I used 0.13.3. Thank you.
