### ISSUE TITLE
[Edge] Cannot disable(mute) microphone input

### ISSUE THREAD

**Issue by aszmyd** [Temasys/AdapterJS#239]
I need a feature to toggle microphone input from user and it seems that Edge is the only one that is broken in this case. 
How i do this:

1. I grab mic stream using `navigator.getUserMedia`
2. I create new Peer connection using [`window.RTCPeerConnection` object](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/RTCPeerConnection)
3. I add the captured mic stream to peer connection instance using [`addStream` method](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/addStream) 
4. When i want to toggle mic input i get [MediaStreamTracks](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack) from microhone input `getAudioTracks` method and looping over them i set `enabled` field to either true or false.

This seems to be working in all browsers except Edge. 
I've checked if the Edge itself is an issue here but my [very simple jsfiddle](https://jsfiddle.net/0u5oftea/3/) (which only locally records audio without any WebRTC connections outside) shows that on Edge the `enabled` flag is actually working fine.

I suppose it might be somehow related to the fact that Adapter is cloning the stream passed to `addStream` method: [adapter.debug.js#L1857](https://github.com/Temasys/AdapterJS/blob/master/publish/adapter.debug.js#L1857)

If its not an issue and the cloning needs to be there, please suggest me how to temporary mute users mic input? 

PS: I've tried to use `removeStream` and `addStream` after each `enable` field toggling but with no luck.

**Comment by aszmyd** [comment]
I found an workaround for this. There are two ways:

1. We can get the current stream using [`getLocalStreams`](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/getLocalStreams) - this way we get actual stream that has been cloned by Adapter
2. We can wait for (`RTCPeerConnection.onaddstream`)[https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/onaddstream] event and store it for future usage. I had troubles with getting the actual stream from `event.stream` field thats way i've saved the stream using the `getLocalStreams` method like this:

```javascript
this._activePcHandler.onaddstream = () => {
    this._activeMicrophoneInputStream = this._activePcHandler.getLocalStreams()[0];
};
```

**Comment by johache** [comment]
I'm happy you found a workaround, however, please note that this part of the code is actually maintained by Google, we only build on top of it.
You may push that issue on their repo, here : https://github.com/webrtc/adapter
