### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by letchoo** [Temasys/AdapterJS#240]
It seems like there are weird characters in the script when loaded in the CDN demos. See [sample demo link here](https://temasys-cdn.s3.amazonaws.com/demos/support-web/adapterjs-0.14.0-encoding.html).  If you open the Web Console, you will see the following line:
> adapter.debug.js:644 Uncaught SyntaxError: Invalid or unexpected token

Then if you click the the `adapter.debug.js` part in that console log line, you will have to scroll to line `644`, and you will see weird characters `â€` in the script. Here's an example of how it's like now:

```
// Check for browser types and react accordingly
if ( (navigator.mozGetUserMedia ||
      navigator.webkitGetUserMedia ||
      (navigator.mediaDevices &&
       navigator.userAgent.match(/Edge\/(\d+).(\d+)$/)))
    && !((navigator.userAgent.match(/android/ig) || []).length === 0 &&
      â€‚â€‚â€‚â€‚(navigator.userAgent.match(/chrome/ig) || []).length === 0 && navigator.userAgent.indexOf('Safari/') > 0)) {
```

The solution right now is to set the `charset="utf-8"` on the `<script>`, or to remove these characters in grunt tasks when compiling for SkylinkJS.

**Comment by johache** [comment]
I feel like you should have a ``<meta>`` tag in you ``<head>``
See http://www.w3schools.com/tags/att_meta_charset.asp

Would that not fix the issue ?
Seems pretty standard to me.

**Comment by letchoo** [comment]
It's true that `<meta>` tag is a standard (the CDN automatically adds it), but these characters should not exist in the code though.

**Comment by johache** [comment]
Try this version, see if that fixes the issue : https://github.com/Temasys/AdapterJS/tree/GH-240-bad-characters

**Comment by johache** [comment]
Ha ha, sorry, I just saw your PR

**Comment by johache** [comment]
PR merged : https://github.com/Temasys/AdapterJS/pull/241

**Comment by letchoo** [comment]
Too late too late!
