### ISSUE TITLE
Safari: attachMediaStream calls undefined setStreamId() function.

### ISSUE THREAD

**Issue by ddejean** [Temasys/AdapterJS#244]
Hi,

We're using the commercial version of the plugin to share the screen of the clients. When starting a screen sharing session, we're using the attachMediaStream() function to show the preview of the capture stream in the webpage.
If we run two screen sharing session, one after the other, the second one fails with the error:
```
TypeError: element.setStreamId is not a function. (In 'element.setStreamId(streamId)', 'element.setStreamId' is undefined)
attachMediaStream — adapter.screenshare.js:2943
showLocalPreview — PresentationViewManager.js:673
_onProjectionPreviewReady — PresentationController.js:509
```

Looking at the adapter code, it seems it try to re-use the previously instantiated <object> but it fails to call the setStreamId method on it. If we comment this call, it works as usual.

Here is a sample of the code we use to attach the stream:
```
[...]
// Get the <video> tag from exposed DOM
var streamPreview = document.getElementById("streamPreview");
streamPreview = attachMediaStream(streamPreview, localStream);
[...]
```
Context:
- Safari version 8 and 10 (version 9 not tested)
- AdapterJS version 0.13.4 (2016-10-03)

Thanks for your help :)

**Comment by johache** [comment]
I just tested against our examples, and it seems to work fine for me (tested on Safari 10) : https://plugin.temasys.com.sg/demo/src/content/getusermedia/screensharing/

Just run `navigator.mediaDevices.getUserMedia(constraints)
  .then(onSuccess).catch(onFailure);` to restart the gum process.

Can I test out on a live sample of yours ?

**Comment by ddejean** [comment]
I tested your example, indeed it works. It seems your test implementation does not provide the possibility to stop the screen sharing (or I didn't see it) and this is exactly the situation that cause the problem with us.

The typical sequence for us is:
```
navigator.mediaDevices.getUserMedia(constraints)
.then(function(stream) {
[...]
var streamPreview = document.getElementById("streamPreview");
streamPreview = attachMediaStream(streamPreview, stream);
[...]
})
.catch(...)

// Then the user stops the screen sharing by clicking somewhere:
var tracks = stream.getVideoTracks();
for (var i in tracks) {
    tracks[i].stop();
}

// Then he wants do do it again but without reloading the page
navigator.mediaDevices.getUserMedia(constraints)
.then(function(stream) {
[...]
var streamPreview = document.getElementById("streamPreview");
streamPreview = attachMediaStream(streamPreview, stream); // The problem happens here
[...]
})
.catch(...)
```

Do you see anything that is not correct ?
As our application is embedded in a multimedia system it is not available on the web. By the way I will try to extract a sample of code that reproduces the problem.

**Comment by ddejean** [comment]
Hum, I found a lead, it seems that somewhere in our UI the object injected by attachMediaStream() was hidden between to screen sharing, and it fails after that. If I don't hide it, or I recreate a new video tag each time, it works correctly. What's strange is that the behavior changed recently without major modifications ...
