### ISSUE TITLE
Screensharing doesn't work

### ISSUE THREAD

**Issue by GuillaumeUnice** [Temasys/AdapterJS#248]
I have installed Chrome/Firefox extension and IE Plugin but:

When I try screensharing on IE 11 on https://plugin.temasys.io/demo/src/content/getusermedia/screensharing/
That works! But only online when I download and run in localhost there is a getUserMedia error.
I have an HTTPS but not register in a PKI that the reason of the issue?

Thanks for all

**Comment by johache** [comment]
Hi,

So the screensharing feature is a paid feature of the plugin.
We enable it on our demos (namely getaroom.io and plugin.temasys.com.sg/demo) for demo and advertisement purposes, but if you want to use it on other domain names, you will need to go for a custom license.

See http://temasys.io/plugin/ for more information.

**Comment by GuillaumeUnice** [comment]
That wrong the problem was I try to use audio with screen sharing and it seems we can't currently... I don't understand why but I can screenshare between IE and Chrome but without sound for peer's screenshare do you have any ideas?

**Comment by GuillaumeUnice** [comment]
Hi,

I buy the plugin and the issue resume :s 

When I print I have the following error

```
		 console.log(AdapterJS.WebRTCPlugin.plugin.HasScreensharingFeature); // true
		 console.log(AdapterJS.WebRTCPlugin.plugin.isScreensharingAvailable); // FALSE !!!
```
I precise the Chrome to IE way run correctly.
The problem is screensharing from IE to Chrome.

If you could reopen the issue because the problem is bind with IE only.

**Comment by johache** [comment]
Hi,

Which company are you a part of ?
If you are a paying customer, you should be sending that issue thought the support portal for immediate and prioritised support.
See http://support.temasys.com.sg/
