### ISSUE TITLE
Safari giving error, how to fix it?

### ISSUE THREAD

**Issue by shamun** [Temasys/AdapterJS#250]
See the BUG seems to be in Temasys plugin: https://github.com/andyet/SimpleWebRTC/issues/527

While using https://cdn.temasys.com.sg/adapterjs/0.13.x/adapter.debug.js, i am getting following error:
```
TypeError: audioContext.createMediaStreamSource is not a function. (In 'audioContext.createMediaStreamSource(stream)', 'audioContext.createMediaStreamSource' is undefined)
```

When i used `https://plugin.temasys.com.sg/demo/src/content/getusermedia/gum/` it works but not when i use it with other WebRTC frameworks (SimpleWebRTC, AppRTC).

![1](http://i.imgur.com/HbyWJbn.png)

![2](http://i.imgur.com/EbE8fjh.png)

![3](http://i.imgur.com/m53kRtA.png)

**Comment by johache** [comment]
The Temasys plugin does not implement the AudioContext MediaStream related API. We only implement the WebRTC spec APIs.
Safari already has an implementation of AudioContext, which does not support MediaStream, and we don't want to override it.

**Comment by shamun** [comment]
Where to find the Temasys Plugin source, is it open-source? i can override it for custom Safari requirement to see if it resolve the issue for SimpleWebRTC. Else SimpleWebRTC community has to stop using SimpleWebRTC which is not nice to see.

**Comment by johache** [comment]
The plugin is not open source.
You can try to update AJS to see if you can shim some implementation of AudioContext, but I think that you will be fairly limited.
