### ISSUE TITLE
iceServers .urls does not allow an Array

### ISSUE THREAD

**Issue by ibc** [Temasys/AdapterJS#26]
According to the current spec `.urls` should accept an URL string or a sequence of them:

```
dictionary RTCIceServer {
      (DOMString or sequence<DOMString>) urls;
```

However the plugin completely ignores the `urls` entries if it contains an Array. This is:

* This works and relay candidates are gathered:
```
iceServers: [{
	urls: 'turn:turn.example.com:1234?transport=udp',
	username: 'foo',
	credential: '1234f'
}]
```
* This does not work (no relay candidates are retrieved at all):
```
iceServers: [{
	urls: ['turn:turn.example.com:1234?transport=udp'],
	username: 'foo',
	credential: '1234f'
}]
```

Is this a limitation? or should it already work?

Thanks a lot.

**Comment by johache** [comment]
Resolved by release 0.8.826 of the plugin.
