### ISSUE TITLE
MediaStreamTrack has no prototype

### ISSUE THREAD

**Issue by ibc** [Temasys/AdapterJS#27]
In order to check how to properly close/stop a MediaStream I check whether the `MediaStreamTrack.prototype.stop` exists or not. However the `MediaStreamTrack` implementation of the plugin has no `prototype` (it is `undefined`).

Would it be easy to add it? Otherwise I'll use another approach to check the existence of the `stop` method.

**Comment by johache** [comment]
Successfully tested the following code:
```javascript
MediaStreamTrack = function() {};
MediaStreamTrack.prototype.stop = function() {};
MediaStreamTrack.getSources = function (callback) {
  AdapterJS.WebRTCPlugin.callWhenPluginReady(function() {
     AdapterJS.WebRTCPlugin.plugin.GetSources(callback);
  });
};
```

However:
1) You will still not be able to call localStream.getVideoTracks().stop(),
2) Given the way the NPAPI/ActiveX interface works, I don't think I will be  to set ```MediaStreamTrack.prototype.stop = the actual class function```
in the future...

Therefore I am not sure this makes sense.

**Comment by ibc** [comment]
2015-01-05 8:51 GMT+01:00 johache <notifications@github.com>:

> Successfully tested the following code:
>
> MediaStreamTrack = function() {};MediaStreamTrack.prototype.stop = function() {};MediaStreamTrack.getSources = function (callback) {
>   AdapterJS.WebRTCPlugin.callWhenPluginReady(function() {
>      AdapterJS.WebRTCPlugin.plugin.GetSources(callback);
>   });
> };
>
> However:
> 1) You will still not be able to call localStream.getVideoTracks().stop(),
>

Ok, my fault, I didn't ask for an empty stop() method, but just for a
prototype object. In my code I check for (typeof
MediaStreamTrack.prototype.stop === 'function') in order to call stop() on
each track or call it on the MediaStream (deprecated in the spec). So by
just adding:

  MediaStreamTrack = function() {};

would be enough :)

But if MediaStreamTrack.prototype.stop does exists and is a function, then
my check will fail.


2) Given the way the NPAPI/ActiveX interface works, I don't think I will be
> to set MediaStreamTrack.prototype.stop = the actual class function
> in the future...
>
> Therefore I am not sure this makes sense.
>

Agreed.


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Temasys/AdapterJS/issues/27#issuecomment-68677242>.
>



-- 
Iñaki Baz Castillo
<ibc@aliax.net>

**Comment by johache** [comment]
But you'd still rather have 
```MediaStreamTrack = function() {};```
than
```MediaStreamTrack = {};```
right?

I have no issue with that.
@serrynaimo @ncurrier JS gurus, can I have it validated by any one of you?

**Comment by ibc** [comment]
Sure. If `MediaStreamTrack` is not a function then it has no `prototype`.

**Comment by nasivuela** [comment]
Any updates on this?
