### ISSUE TITLE
Replacing stream doesn't work.

### ISSUE THREAD

**Issue by zdila** [Temasys/AdapterJS#276]
In Safari 10 if we set new `<param name="streamId" value="..." />` in the existing `object` then there is no video shown until we make our app fullscreen (using fullscreen api) or return from fullscreen. It seems to be a bug of Themasys plugin. We are using latest free version.

**Comment by zdila** [comment]
Workaround:

1. remove `object` element from the DOM
2. set its `<param name="streamId" value="..." />`
3. put `object` element back to DOM (to the same place)

**Comment by johache** [comment]
The browser doesn't inform the plugin when a child element is modified.
Basically, we only ready the <param> when the plugin object is instantiated, which, as you figured out, is when you inject it into the DOM.

This is not a bug, it's just the way it works.
