### ISSUE TITLE
Different streams with equal stream.id

### ISSUE THREAD

**Issue by zdila** [Temasys/AdapterJS#279]
If we use Janus Gateway and multiple peerConnections then every remote stream has same id `janus` and so we can't show two different remote videos.

**Comment by zdila** [comment]
Following SDP mangling seems to help:

```
        const id = Math.random().toString().slice(2);
        sdp = sdp
          .replace(/\bmslabel:janus\b/g, `mslabel:${id}`)
          .replace(/\bmsid:janus\b/g, `mid:${id}`)
          .replace(/\bWMS janus\b/g, `WMS ${id}`);
```

**Comment by johache** [comment]
The plugin does rely on stream ids to know what to render.
This is a know limitation. Munging the SDP is indeed a solution.
