### ISSUE TITLE
Safari11 WebRTC support

### ISSUE THREAD

**Issue by aszmyd** [Temasys/AdapterJS#280]
[Safari 11](https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Safari_11_0/Safari_11_0.html) will have WebRTC native support it seems. 
Will this plugin work with it? It would be nice if it would just work when Safari11 will be officially released.

**Comment by zdila** [comment]
It works for us.

**Comment by aszmyd** [comment]
ok. what version of TemaSys plugin do You use? The adapter is making a detection and our current version (`0.14.0`) is just detecting mobile Safari11 as unsupported. Is it working for You on both mobile  and desktop?

**Comment by zdila** [comment]
We are not using AdapterJS, only Temasys WebRTC plugin to support Safari < 11. We have our own JS that communicates with plugin (much of the code borrowed from AdapterJS). We also use https://github.com/webrtc/adapter.

> The adapter is making a detection and our current version (0.14.0) is just detecting mobile Safari11 as unsupported.

Maybe try to modify AdapterJS browser detection code.

> Is it working for You on both mobile and desktop?

Our solution works on both. In Safari 11 it is just not using the plugin.

**Comment by zdila** [comment]
> ...only Temasys WebRTC plugin to support Safari < 11

Actually we use browser plugin also for Safari 11 if it is installed. It is to support VP8 because native implementation supports only H264.

**Comment by johache** [comment]
There is already a branch that that started this integration.

For now, on Safari 11 (macOS, and iOS), we default to the native implementation.
It means no screensharing, no VP8/VP9.

Eventually, we plan on having a flag to override the native implementation with the plugin implementation (macOS only, no plugins on iOS).
Eventually meaning by the time High Sierra releases.

**Comment by aszmyd** [comment]
@zdila @johache thanks!
