### ISSUE TITLE
Merging this project to the official WebRTC Adapter.js

### ISSUE THREAD

**Issue by Cheedoong** [Temasys/AdapterJS#281]
I posted here:
https://github.com/webrtc/adapter/issues/639

Hope they will accept it.

**Comment by johache** [comment]
Hi,

Thanks for effort, but I don't see this happening any time soon.
The point of webrtc-adapter is to shim the differences between the browsers native implementations.

The Temasys plugin comes on top of it, and therefore it's coherent for AdapterJS to remain an extension of webrtc-adapter.

Regards,
J-O H
