### ISSUE TITLE
rtcTRACKENVENT undefined 

### ISSUE THREAD

**Issue by pnoyelle** [Temasys/AdapterJS#294]
Hi, on firefox 45 RTCTRACKENVENT is undefinned and cause an error ;
due to a check on rtcpeerconnection instead of rtcTRACKENVENT on line 4174, corriged by webrtc adapter team : on https://github.com/webrtc/adapter/pull/670/files

**Comment by johache** [comment]
Hi,
We try to stay relative up to date with webrtc-adapter.
The dependency will probably be updated within a month.
