### ISSUE TITLE
callWhenPluginReady() is slow

### ISSUE THREAD

**Issue by ibc** [Temasys/AdapterJS#30]
```
  AdapterJS.WebRTCPlugin.callWhenPluginReady = function (callback) {
    var checkPluginReadyState = setInterval(function () {
      if (AdapterJS.WebRTCPlugin.pluginState === AdapterJS.WebRTCPlugin.PLUGIN_STATES.READY) {
        clearInterval(checkPluginReadyState);
        callback();
      }
    }, 100);
  };
```

This means that, even if the plugin state is READY (this is, the DOM is "complete") it will take 100ms for the callback to be called.

If plugin state is READY this function should immediately execute the callback.

**Comment by johache** [comment]
Correct,
Corrected, upgraded version number to 0.10.1 and pushed
