### ISSUE TITLE
How to display multiple Media streams in iPhone safari?

### ISSUE THREAD

**Issue by dongkai1993** [Temasys/AdapterJS#301]
When playing a new media stream, the other media streams which were played will be paused, how can I avoid it?

**Comment by johache** [comment]
Can you be more specific ?
If you start playing a stream in a <video> tag, it will replace the stream currently played.
If you have other streams rendered in other <video> tags, they should not stop.

**Comment by dongkai1993** [comment]
Only in iPhone safari, I playing a stream, other stream will be stoped.

**Comment by johache** [comment]
I tested an was able to reproduce on getaroom.io.
I haven;'t looked much into it, but that's probably an iOS issue.
I would suggest opening a ticket with Apple.

**Comment by dongkai1993** [comment]
Thank you!
