### ISSUE TITLE
'MediaStreamTrack' is undefined

### ISSUE THREAD

**Issue by CSantosM** [Temasys/AdapterJS#307]
I'm trying to include Temasys Plugin in my app and i have the error **'MediaStreamTrack' is undefined**
If I'm not wrong, AdapterJS include MediaStreamTrack polyfills but I have this error... I am starting my app with 
```
AdapterJS.webRTCReady(function(isUsingPlugin) {
   AdapterJS.WebRTCPlugin.callWhenPluginReady(function() {
      initApp();
   });
});
```
What am i doing bad?
Thank you in advance.

**Comment by johache** [comment]
- Which browser are you running ?
- `MediaStreamTrack` when using the plugin is only defined to give access to `MediaStreamTrack.getSources`. It doesn't define a constructor.
