### ISSUE TITLE
How to close IE11 devices access permission prompt box

### ISSUE THREAD

**Issue by chenhl05** [Temasys/AdapterJS#312]
![ie 浏览器调起摄像头](https://user-images.githubusercontent.com/20461097/73367424-80dd7900-42ea-11ea-8bee-bbf840cd2b80.png)
When I use IE11 to open page, it says "Devices Access Permission.This page would like access to share your camera and/or microphone.Allow this?...".Can this prompt box not be displayed by default?

**Comment by johache** [comment]
Hi @chenhl05 ,

Automatically granting access to devices is a premium feature.
Please contact Temasys for more information: https://temasys.io/products/temasys-webrtc-plugin/
