### ISSUE TITLE
IE11 on Windows 8 listing unplugged camera

### ISSUE THREAD

**Issue by JamieMcDonnell** [Temasys/AdapterJS#36]
My colleague has a logitech c920 camera installed on their system, and it is plugged in when starting IE.

He later unplugs the camera, and reloads the page that uses the Temasys plugin, calling gUM.

The Temasys plugin shows the camera that has been unplugged, and trying to access it causes a gUMFailed event.

If the camera is not plugged in it should not be visible in the in the device list.
![screen shot 2015-01-15 at 14 29 46](https://cloud.githubusercontent.com/assets/647732/5758269/27470d92-9cc4-11e4-87a0-3228a04ec769.png)

**Comment by agouaillard** [comment]
You are right, this is a bug.

The plugin is a singleton, a single instance exists at a time, for a given
browser, to be able to share the local cams/streams m between tabs. It is
very likely that we do not repopulate the input device list after the first
initialization, We will double check that.

Could you in the future send the bugs related to the plugin on the plugin
mailing list:
https://groups.google.com/forum/#!forum/temasys-discuss-webrtcplugin

thank you in advance.

Alex.

On Thu, Jan 15, 2015 at 9:38 PM, JamieMcDonnell <notifications@github.com>
wrote:

> My colleague has a logitech c920 camera installed on their system, and it
> is plugged in when starting IE.
>
> He later unplugs the camera, and reloads the page that uses the Temasys
> plugin, calling gUM.
>
> The Temasys plugin shows the camera that has been unplugged, and trying to
> access it causes a gUMFailed event.
>
> If the camera is not plugged in it should not be visible in the in the
> device list.
> [image: screen shot 2015-01-15 at 14 29 46]
> <https://cloud.githubusercontent.com/assets/647732/5758269/27470d92-9cc4-11e4-87a0-3228a04ec769.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Temasys/AdapterJS/issues/36>.
>



-- 
Alex. Gouaillard, PhD, PhD, MBA
------------------------------------------------------------------------------------
CTO - Temasys Communications, S'pore / Mountain View
President - CoSMo Software, Cambridge, MA
------------------------------------------------------------------------------------
sg.linkedin.com/agouaillard

   -

**Comment by JamieMcDonnell** [comment]
Hi Alex, thanks for taking a look - sure I will post them here in future -
will you move this (and others I may have posted in the AdapterJS git repo)
to the google group?

Thanks

Jamie

On 16 January 2015 at 13:09, alex gouaillard <notifications@github.com>
wrote:

> You are right, this is a bug.
>
> The plugin is a singleton, a single instance exists at a time, for a given
> browser, to be able to share the local cams/streams m between tabs. It is
> very likely that we do not repopulate the input device list after the
> first
> initialization, We will double check that.
>
> Could you in the future send the bugs related to the plugin on the plugin
> mailing list:
> https://groups.google.com/forum/#!forum/temasys-discuss-webrtcplugin
>
> thank you in advance.
>
> Alex.
>
> On Thu, Jan 15, 2015 at 9:38 PM, JamieMcDonnell <notifications@github.com>
>
> wrote:
>
> > My colleague has a logitech c920 camera installed on their system, and
> it
> > is plugged in when starting IE.
> >
> > He later unplugs the camera, and reloads the page that uses the Temasys
> > plugin, calling gUM.
> >
> > The Temasys plugin shows the camera that has been unplugged, and trying
> to
> > access it causes a gUMFailed event.
> >
> > If the camera is not plugged in it should not be visible in the in the
> > device list.
> > [image: screen shot 2015-01-15 at 14 29 46]
> > <
> https://cloud.githubusercontent.com/assets/647732/5758269/27470d92-9cc4-11e4-87a0-3228a04ec769.png>
>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Temasys/AdapterJS/issues/36>.
> >
>
>
>
> --
> Alex. Gouaillard, PhD, PhD, MBA
> ------------------------------------------------------------------------------------
>
> CTO - Temasys Communications, S'pore / Mountain View
> President - CoSMo Software, Cambridge, MA
> ------------------------------------------------------------------------------------
>
> sg.linkedin.com/agouaillard
>
> -
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Temasys/AdapterJS/issues/36#issuecomment-70245348>.
>



-- 
------------------------------
Jamie McDonnell | User Experience Design Evangelist and Developer |
 eFace2Face

mobile: (+420) 777 608 442 | email: jamie.mcdonnell@eface2face.com | web:
eface2face.com <http://www.eface2face.com>
[image: eface2face logo]  <http://www.eface2face.com>

[image: View our company profile on LinkedIn]
<http://www.linkedin.com/company/eface2face>

This electronic communication and any files transmitted with it, or
attached to it, are confidential and are intended solely for the use of the
individual or entity to who it is addressed and may contain information
that is confidential, legally privileged, protected by privacy laws, or
otherwise restricted from disclosure to anyone else. If you are not the
intended recipient or the person responsible for delivering the e-mail to
the intended recipient, be advised that you have received this e-mail in
error, and that any use, dissemination, forwarding, printing, or copying of
this e-mail is strictly prohibited. If you received this e-mail in error,
please return the e-mail to the sender, delete it from your computer and
destroy any printed copy of it. Although our company attempts to sweep
e-mail and attachments for viruses, it does not guarantee that either are
virus-free and accepts no liability for any damage sustained as a result of
viruses.
------------------------------

**Comment by agouaillard** [comment]
no problem.

I will let JO decides if he wants to nave them or not. He is the "plug-in
man"(TM). He decides.

Alex.

On Fri, Jan 16, 2015 at 9:05 PM, JamieMcDonnell <notifications@github.com>
wrote:

> Hi Alex, thanks for taking a look - sure I will post them here in future -
> will you move this (and others I may have posted in the AdapterJS git
> repo)
> to the google group?
>
> Thanks
>
> Jamie
>
> On 16 January 2015 at 13:09, alex gouaillard <notifications@github.com>
> wrote:
>
> > You are right, this is a bug.
> >
> > The plugin is a singleton, a single instance exists at a time, for a
> given
> > browser, to be able to share the local cams/streams m between tabs. It
> is
> > very likely that we do not repopulate the input device list after the
> > first
> > initialization, We will double check that.
> >
> > Could you in the future send the bugs related to the plugin on the
> plugin
> > mailing list:
> > https://groups.google.com/forum/#!forum/temasys-discuss-webrtcplugin
> >
> > thank you in advance.
> >
> > Alex.
> >
> > On Thu, Jan 15, 2015 at 9:38 PM, JamieMcDonnell <
> notifications@github.com>
> >
> > wrote:
> >
> > > My colleague has a logitech c920 camera installed on their system, and
> > it
> > > is plugged in when starting IE.
> > >
> > > He later unplugs the camera, and reloads the page that uses the
> Temasys
> > > plugin, calling gUM.
> > >
> > > The Temasys plugin shows the camera that has been unplugged, and
> trying
> > to
> > > access it causes a gUMFailed event.
> > >
> > > If the camera is not plugged in it should not be visible in the in the
> > > device list.
> > > [image: screen shot 2015-01-15 at 14 29 46]
> > > <
> >
> https://cloud.githubusercontent.com/assets/647732/5758269/27470d92-9cc4-11e4-87a0-3228a04ec769.png>
>
> >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/Temasys/AdapterJS/issues/36>.
> > >
> >
> >
> >
> > --
> > Alex. Gouaillard, PhD, PhD, MBA
> >
> ------------------------------------------------------------------------------------
>
> >
> > CTO - Temasys Communications, S'pore / Mountain View
> > President - CoSMo Software, Cambridge, MA
> >
> ------------------------------------------------------------------------------------
>
> >
> > sg.linkedin.com/agouaillard
> >
> > -
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Temasys/AdapterJS/issues/36#issuecomment-70245348>.
> >
>
>
>
> --
> ------------------------------
> Jamie McDonnell | User Experience Design Evangelist and Developer |
> eFace2Face
>
> mobile: (+420) 777 608 442 | email: jamie.mcdonnell@eface2face.com | web:
> eface2face.com <http://www.eface2face.com>
> [image: eface2face logo] <http://www.eface2face.com>
>
> [image: View our company profile on LinkedIn]
> <http://www.linkedin.com/company/eface2face>
>
> This electronic communication and any files transmitted with it, or
> attached to it, are confidential and are intended solely for the use of
> the
> individual or entity to who it is addressed and may contain information
> that is confidential, legally privileged, protected by privacy laws, or
> otherwise restricted from disclosure to anyone else. If you are not the
> intended recipient or the person responsible for delivering the e-mail to
> the intended recipient, be advised that you have received this e-mail in
> error, and that any use, dissemination, forwarding, printing, or copying
> of
> this e-mail is strictly prohibited. If you received this e-mail in error,
> please return the e-mail to the sender, delete it from your computer and
> destroy any printed copy of it. Although our company attempts to sweep
> e-mail and attachments for viruses, it does not guarantee that either are
> virus-free and accepts no liability for any damage sustained as a result
> of
> viruses.
> ------------------------------
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Temasys/AdapterJS/issues/36#issuecomment-70250705>.
>



-- 
Alex. Gouaillard, PhD, PhD, MBA
------------------------------------------------------------------------------------
CTO - Temasys Communications, S'pore / Mountain View
President - CoSMo Software, Cambridge, MA
------------------------------------------------------------------------------------
sg.linkedin.com/agouaillard

   -

**Comment by johache** [comment]
Hi Jamie,
Please do open a new thread on our plugin mailing list: groups.google.com/forum/#!forum/temasys-discuss-webrtcplugin

You can close this one once this is done

(FYI, I reproduced the bug, I will give a more complete answer on the plugin mailing list)
