### ISSUE TITLE
Installing Temasys plugin in IE11 on Windows 7 causes IE to crash on GUM

### ISSUE THREAD

**Issue by JamieMcDonnell** [Temasys/AdapterJS#37]
I have just uninstalled and re-installed Temasys in my Windows 7 VM using the following link:
http://bit.ly/1w0jWB1

I understand this is the link to your latest version of the plugin, but once installed, it shows v0.8.801.0

Once this version is installed, restarting IE and calling GUM crashes IE.

I do not understand why the old version of your plugin is getting installed from this link? Any ideas?

Here is the log from the crash:
Podpis problému:
  Název události problému:	APPCRASH
  Název aplikace:	IEXPLORE.EXE
  Verze aplikace:	11.0.9600.17207
  Časové razítko aplikace:	53a20c50
  Název chybného modulu:	npTemWebRTCPlugin.dll
  Verze chybného modulu:	0.8.801.0
  Časové razítko chybného modulu:	54365535
  Kód výjimky:	c0000005
  Posun výjimky:	0059d786
  Verze operačního systému:	6.1.7601.2.1.0.768.3
  ID národního prostředí:	1029
  Další informace 1:	0a9e
  Další informace 2:	0a9e372d3b4ad19135b953a78882e789
  Další informace 3:	0a9e
  Další informace 4:	0a9e372d3b4ad19135b953a78882e789

Přečtěte si prohlášení o zásadách ochrany osobních údajů online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0405

Pokud není k dispozici Prohlášení o zásadách ochrany osobních údajů online, přečtěte si toto prohlášení offline:
  C:\Windows\system32\cs-CZ\erofflps.txt

**Comment by JamieMcDonnell** [comment]
Note, I have downloaded and run the installer manually directly from your site and receive the same issue - I get no notification that any update for the plugin is available - perhaps the installer on your website needs updating? Thanks.

**Comment by johache** [comment]
Is there any chance your browser cached

**Comment by johache** [comment]
*is there any chance your browser cached the download?

**Comment by johache** [comment]
Hey, just checked your link from my computer, better than from my phone:
The link you sent me was for the wrong version (check your download manager).
The links on this page were wrong, corrected : https://temasys.atlassian.net/wiki/display/TWPP/WebRTC+Plugins

The links provided by the plugin (popup at the top of you browser) should be correct.

GUM should not crash anyhow. In what context are you using the plugin?

**Comment by JamieMcDonnell** [comment]
ok thanks for updating the links in the page - I am using the plugin in the
client side of our application - it is loaded within an iFrame currently,
and GUM is called when the user selects how they want to connect (camera +
mic, mic only, chat only).

GUM definitely crashes the browser in that context on Win 7 - see for
yourself in the log.

Thanks for taking a look

J

On 16 January 2015 at 10:16, Jacques-Olivier Haché <notifications@github.com
> wrote:

> Hey, just checked your link from my computer, better than from my phone:
> The link you sent me was for the wrong version (check your download
> manager).
> The links on this page were wrong, corrected :
> https://temasys.atlassian.net/wiki/display/TWPP/WebRTC+Plugins
>
> The links provided by the plugin (popup at the top of you browser) should
> be correct.
>
> GUM should not crash anyhow. In what context are you using the plugin?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Temasys/AdapterJS/issues/37#issuecomment-70227015>.
>



-- 
------------------------------
Jamie McDonnell | User Experience Design Evangelist and Developer |
 eFace2Face

mobile: (+420) 777 608 442 | email: jamie.mcdonnell@eface2face.com | web:
eface2face.com <http://www.eface2face.com>
[image: eface2face logo]  <http://www.eface2face.com>

[image: View our company profile on LinkedIn]
<http://www.linkedin.com/company/eface2face>

This electronic communication and any files transmitted with it, or
attached to it, are confidential and are intended solely for the use of the
individual or entity to who it is addressed and may contain information
that is confidential, legally privileged, protected by privacy laws, or
otherwise restricted from disclosure to anyone else. If you are not the
intended recipient or the person responsible for delivering the e-mail to
the intended recipient, be advised that you have received this e-mail in
error, and that any use, dissemination, forwarding, printing, or copying of
this e-mail is strictly prohibited. If you received this e-mail in error,
please return the e-mail to the sender, delete it from your computer and
destroy any printed copy of it. Although our company attempts to sweep
e-mail and attachments for viruses, it does not guarantee that either are
virus-free and accepts no liability for any damage sustained as a result of
viruses.
------------------------------

**Comment by johache** [comment]
Can you check
- that you don't have two plugin installed on your computer (control panel)
- if this test works for you : https://plugin.temasys.com.sg/demo/samples/web/content/getusermedia/iframe/index.html

Cheers,
J-O

**Comment by JamieMcDonnell** [comment]
hi Jacques,

Thanks, though I now have the latest version of the plugin installed (yes,
there is only one version, I never saw 2 in the uninstall panel in Windows).

The link above works in IE with the latest version, but when I was using
the install link from your website (that has now been updated) IE was
crashing. This was in a VM of Windows 7 under parallels on mac, though
other versions work as expected.

Hope that helps?

Thanks

Jamie

On 19 January 2015 at 03:18, Jacques-Olivier Haché <notifications@github.com
> wrote:

> Can you check
>
>    - that you don't have two plugin installed on your computer (control
>    panel)
>    - if this test works for you :
>    https://plugin.temasys.com.sg/demo/samples/web/content/getusermedia/iframe/index.html
>
> Cheers,
> J-O
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Temasys/AdapterJS/issues/37#issuecomment-70438895>.
>



-- 
------------------------------
Jamie McDonnell | User Experience Design Evangelist and Developer |
 eFace2Face

mobile: (+420) 777 608 442 | email: jamie.mcdonnell@eface2face.com | web:
eface2face.com <http://www.eface2face.com>
[image: eface2face logo]  <http://www.eface2face.com>

[image: View our company profile on LinkedIn]
<http://www.linkedin.com/company/eface2face>

This electronic communication and any files transmitted with it, or
attached to it, are confidential and are intended solely for the use of the
individual or entity to who it is addressed and may contain information
that is confidential, legally privileged, protected by privacy laws, or
otherwise restricted from disclosure to anyone else. If you are not the
intended recipient or the person responsible for delivering the e-mail to
the intended recipient, be advised that you have received this e-mail in
error, and that any use, dissemination, forwarding, printing, or copying of
this e-mail is strictly prohibited. If you received this e-mail in error,
please return the e-mail to the sender, delete it from your computer and
destroy any printed copy of it. Although our company attempts to sweep
e-mail and attachments for viruses, it does not guarantee that either are
virus-free and accepts no liability for any damage sustained as a result of
viruses.
------------------------------

**Comment by johache** [comment]
Hi Jamie,

I am going to close this issue as - as far as I can see - there are no issues with the current plugin downloaded from our websites and/or plugin auto-update popup.
If there is an issue with an older version, there isn't much we can do about that. Once it's out there, it's out there. Again, the latest versions don't show this problem for me.

You can re-open the issue if you think there is still work to do.
