### ISSUE TITLE
Get raw audio data from media stream?

### ISSUE THREAD

**Issue by rikner** [Temasys/AdapterJS#48]
I'd like to pipe the microphone audio data into a Web Audio API chain. In Chrome or Firefox, I would just create a MediaStreamSource with AudioContext.createMediaStreamSource(mediaStream) (see https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createMediaStreamSource) and pass the mediaStream I get from the onSuccess event from getUserMedia.

Anyhow the AudioContext of Safari does not provide the createMediaStreamSource() method, since it makes no sense without (native) getUserMedia. The method is also not polyfilled by AdapterJS. I wonder if I could instead access the raw audio data from the temasys mediaStream JSAPI-object and write into a BufferSourceNode. Is anyone aware if this is possible?
Or are there even any plans to polyfill the AudioContext.createMediaStreamSource() in Safari. That would be awesome!

**Comment by serrynaimo** [comment]
@johache something you want to look at and consider for the Plugin? Thanks @rikner for pointing this out.

**Comment by agouaillard** [comment]
Hi Thomas, all,

<brief>
We are very reluctant at this stage to go into the web audio API. The plumbing needed to bridge media streams and web audio is not trivial, and we would end up replacing a lot of browser native component. 

<long>
1. The original pledge was to support only Webrtc and all Webrtc. To do it well we need to replace audio and video tags and support corresponding APIs. That was unexpected and it leads to a lot of extra work. It is not fully done today and some request for audio and video API are still pending and take precedence. we are now very careful at extending support to new objects/methods/API.

2. On the medium / long term, we are working on porting Webrtc to safari and other browsers missing Webrtc support today. The dev is shared, the maintenance is also shared, that s a scope where I would be more confident to spend the extra mile flirt to support web audio.

Cheers

Alex

**Comment by sasgit** [comment]
Hi-

Is there any timeframe for having AudioContext.createMediaStreamSource() in Safari? Or Is there any workaround to get live audio input samples from microphone?

Thanks,
Sasi

**Comment by johache** [comment]
Not as far as I know.

**Comment by rikner** [comment]
Thx for explanation. I just hoped, that if even there is no official support for AudioContext.createMediaStreamSource(), it would be possible to access the audio buffer somehow to get the raw samples, that have would been all I need.
