### ISSUE TITLE
Make AdapterJS work with EasyRTC

### ISSUE THREAD

**Issue by fbernhard** [Temasys/AdapterJS#49]
We had to patch AdapterJS slightly to make it work with EasyRTC, see comment here:

https://github.com/priologic/easyrtc/issues/121#issuecomment-78211330

Basically, AdapterJS' *attachMediaSource* replaces the *video* tag with an *object* tag. Later on,  *attachMediaSource* fails if one passes a newly created *object* due to missing properties and functions.

**Comment by serrynaimo** [comment]
@johache

**Comment by johache** [comment]
I had a very quick look at it two days ago.
Most of it sounds very reasonable. 
I will come back to you when I have more time to test and validate everything.

**Comment by johache** [comment]
Hi fbernhard,
I still very interested in merging your patch. I just happen to have little time to allocate to it right now. I hope to get to it within the next two weeks.
What would really help me is a test page / test scenario to make sure that easy RTC actually works once the integration is done.
Would you have a link to something like that?

**Comment by fbernhard** [comment]
Hi Jacques-Olivier,

I have made a test against easyRTC's "demo_audio_video_simple.html" from their beta branch (commit ff6ec74c3b ) this morning, to make sure. You have to change the following:

1) Remove their "adapter.js" implementation in the top part of "api/easyrtc.js" (everything before "var Easyrtc = function() {")
2) Include your patched adapter.js before easyrtc.js in the demo html file

I get an easyRTC warning about video resolution, otherwise it worked fine (Chrome <-> Safari).

You can also create a free test account with our Veeting Rooms and test it there if you like.

Hope it helps!

**Comment by johache** [comment]
@letchoo @serrynaimo Just pushed a PR

**Comment by agouaillard** [comment]
Guys, make sure to have a common test with easyrtc, optimally with a maintainer on both side. otherwise, we need to maintain one test by ourselves like for the google samples. But keep a test in the test suite for this functionality, please.
