### ISSUE TITLE
Safari/Explorer plugin bugs/features

### ISSUE THREAD

**Issue by ekzobrain** [Temasys/AdapterJS#51]
Using latest plugin version 0.8.826, Safari 7.1, Mac OSX 10.9 Maverics

1.It would be great to have a public documentation like MDN or MSDN, which would describe functionality implemented in your plugin.
2. These methods seem to be not implemented: MediaStream.getTracks(), RTCPeerConnection.removeStream(), at least in Safari 7.1 their type is undefined. Both of them exist in latest W3C Draft and are implemented in Chrome and Firefox. 
3. Plugin causes Safari to freeze when closing connection in this order:
1. call RTCPeerConnection.close() -> call MediaStream.stop() for local stream from context of oniceconnectionstatechange (iceConnectionState=closed) callback. This sequence always freezes Safari.
2. call MediaStream.stop() for local stream -> call RTCPeerConnection.close(). This sequence freezes Safari from time to time (not always).

May be it is some how related to #23 ?

**Comment by letchoo** [comment]
Hi @soulhunter1987,

We are working to have a public documentation on the next release, and `MediaStream.getTracks()` should be polyfilled for the next release as well.

Regarding point no 3, I believe @johache can assist you further

**Comment by johache** [comment]
Hi,

1. For now we only have this page https://temasys.atlassian.net/wiki/display/TWPP/WebRTC+Plugins. For more detail, the plugin is expected to implement the specification as here:
http://www.w3.org/TR/webrtc/#mediastream 
and http://www.w3.org/TR/mediacapture-streams/#widl-MediaStream-getTracks-sequence-MediaStreamTrack
However, I agree that a document listing what is or isn't actually implemented would be good to have

2. Not implemented yet. It should be fairly easy; You should find it in the next release.

3. Yes, same as https://github.com/Temasys/AdapterJS/issues/23. We have been struggling with issue for a while and are still working on it.

**Comment by z0r1k** [comment]
Is there a roadmap posted somewhere? 
When do you plan to release an update? For my use-case having stream removed is crucial as I mentioned here: https://github.com/Temasys/AdapterJS/issues/77
