### ISSUE TITLE
Plugin does not launch in IE

### ISSUE THREAD

**Issue by ekzobrain** [Temasys/AdapterJS#56]
IE 11.0.9600.xxx Windows 7 SP1 x64.

Intalled plugin, restarted IE, tried to make a call, but got "navigator.getUserMedia is undefined". window.getUserMedia is also undefined. "AdapterJS.onwebrtcready" does not fire, no errors in developer console except when trying to access WebRTC methods as described above. Extension details:

<pre>
Name:                          Plugin allowing browser without native handling of WebRTC to actually use it
Vendor:                     (Not verified) Temasys
Type:                          ActiveX element
Arch:                         32-bit
Version:                       0.8.826
File date:                   ‎3 ‎february ‎2015 , ‏‎12:04
Last access date:      ‎1 ‎april ‎2015, ‏‎14:11
Class ID:                    {38CD4193-5EEE-5B7E-BA60-9AF497EE2C59}
Usage count:            7
Blocks count:            0
File:                         npTemWebRTCPlugin.dll
Directory:                        C:\Users\Дмитрий\AppData\Roaming\Tem\TemWebRTCPlugin\0.8.826
</pre>

**Comment by johache** [comment]
1. Did you make sure your implementation of AdapterJS.onwebrtcready wasn't overloaded?
2. Can you make sure the plugin is enabled on your machine (it will only appears in the list of you are on a website that uses it).
![screen shot 2015-04-01 at 2 39 35 pm](https://cloud.githubusercontent.com/assets/3684583/6953272/129607aa-d87d-11e4-81e4-fa648c1cadde.png)
3. What website are you trying to use? Can you try https://plugin.temasys.com.sg/demo/samples/web/content/getusermedia/gum/index.html
It should start GUM automatically.

If all that is ok I will need more detail about your scenario to help you.

**Comment by soulhunter1987** [comment]
1. It fires as expected in Safari, I do not have any browser-specific code there
2. Yes, it is in list and enabled
3. On this page nothing happens either.

Our WebRTC test page is http://robotour.netcitylife.ru/test/call. Email me, please, for login and password, if you'll need access. da dog netcitylife dot ru

**Comment by johache** [comment]
Hum, I don't see an at in your email address. But you can send me those logins at
jo.hache at temasys dot com dot sg

**Comment by soulhunter1987** [comment]
dog = at :)

**Comment by soulhunter1987** [comment]
I've set up breakpoints and found that code execution simply stops after this line (757), when plugin is installed:
var axo = new ActiveXObject(comName + '.' + plugName);
Any code later doesn't get called, no exception, just nothing. May be it is a problem inside a plugin inself causing such behavior? I have Windows installed under Parallels Desktop VM. Do you have any verbose-enabled version of the installer, so that I could monitor any errors happening inside?

**Comment by temapavloff** [comment]
I got exactly the same issue in IE 11 on Window 8.1. Have you guys found out any solution?

**Comment by johache** [comment]
The plugin is expected to work on Windows 8.1.
It works well on our test machines.
Can you check this example as well as what's in my first answser ? 
plugin.temasys.com.sg/demo/samples/web/content/getusermedia/gum/index.html

**Comment by Hetanos** [comment]
Hi guys!
I have exactly the same problem 
stops working at this line: var axo = new ActiveXObject(comName + '.' + plugName)) 
Demo: https://plugin.temasys.com.sg/demo/samples/web/content/getusermedia/gum/index.html
OS: Windows 8.1 pro x64
Browser: Internet Explorer 11
Result: ![image](https://cloud.githubusercontent.com/assets/16030356/11419595/ee5dc400-9441-11e5-9fe0-fc496de8a6c5.png)

**Comment by halben** [comment]
Make sure "ActiveX filtering" is turned off.
