### ISSUE TITLE
Plugin i10n

### ISSUE THREAD

**Issue by ekzobrain** [Temasys/AdapterJS#58]
What do you think about it? It would be great to allow localization of installation/GUM popups via separate javascript language files/plugin initialization settings. I could help with making a Russian language pack. Natively implemented GUM popups in Chrome/Firefox are, of course, localized :)

**Comment by serrynaimo** [comment]
It's on the list of things, but still many other priorities ahead of it. Will post here when we get to it! Thanks :)
