### ISSUE TITLE
RTCIceServer.urls now supported by firefox

### ISSUE THREAD

**Issue by soulhunter1987** [Temasys/AdapterJS#61]
Since version 38 (GA will be released in May) FF supports RTCIceServer.urls property and throws deprecation warning when using RTCIceServer.url. So FF RTCPeerConnection polyfill should be changed to:

```javascript
RTCPeerConnection = function (pcConfig, pcConstraints) {
    if (webrtcDetectedVersion < 38) {
      AdapterJS.maybeFixConfiguration(pcConfig);
    }
    return new mozRTCPeerConnection(pcConfig, pcConstraints);
  };
```

**Comment by johache** [comment]
Fixed with 0.13.1.
