### ISSUE TITLE
On plugin update

### ISSUE THREAD

**Issue by jauhenk** [Temasys/AdapterJS#65]
Guys, do you have any events for plugin as onReadyForUpdate or any other update configs? I can't find any info about it.
Thanks!

**Comment by johache** [comment]
Hi Jauhenk,

We do not.
At the moment the plugin itself if generating the banner that tells the user that an update is ready.
I think we could add such an event, but it won't before a little while.

**Comment by jauhenk** [comment]
Johache, also you have HasAutoupdateFeature property in the plugin object. Is it possible to do something with it?
By the way plugin is really cool. Thank you:)

**Comment by johache** [comment]
This is just a read-only accessor on a flag.
We can turn the auto-update off for contracted plugins. This basically allows one to verify whether the flag is ON or OFF.

**Comment by jauhenk** [comment]
Got it. Thanks!
