### ISSUE TITLE
IE crashed

### ISSUE THREAD

**Issue by jauhenk** [Temasys/AdapterJS#67]
Hey one more again.
There were IE crashes when plugin found updates.
There was no issue before new plugin version became available and after plugin update.

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	IEXPLORE.EXE
  Application Version:	11.0.9600.17416
  Application Timestamp:	5452eed9
  Fault Module Name:	npTemWebRTCPlugin.dll
  Fault Module Version:	0.8.826.0
  Fault Module Timestamp:	54d048cc
  Exception Code:	c0000005
  Exception Offset:	005aa380
  OS Version:	6.3.9600.2.0.0.256.4
  Locale ID:	1033
  Additional Information 1:	5861
  Additional Information 2:	5861822e1919d7c014bbb064c64908b2
  Additional Information 3:	a10f
  Additional Information 4:	a10ff7d2bb2516fdc753f9c34fc3b069

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\WINDOWS\system32\en-US\erofflps.txt

**Comment by serrynaimo** [comment]
Thanks @jauhenk. Our team is looking into it

**Comment by agouaillard** [comment]
Anybody tried to reproduce this?

**Comment by priyanka-narasingu** [comment]
Hi Eugene,
Could you provide information on when does the crash occur? e.g During the peers joining the room or while getting the local user media

**Comment by johache** [comment]
I just made a quick test with the following scenario:
- have 0.8.826 installed
- go to https://plugin.temasys.com.sg/demo/samples/web/content/getusermedia/gum/index.html and validate the popup to see the plugin rendering
- Click on the update popup at the top, validate the download and wait for it to be done
- Run the downloaded installer (0.8.836 today)

Results: 
- no plugin crash
- the plugin version used by IE stays 0.8.826 until IE is restarted
- after restarting , IE uses 0.8.836.

Jauhenk: Am I following the wrong scenario? Am I missing something?

**Comment by jauhenk** [comment]
Hey guys, thank you for your responses. I'm working with commercial version now and can't reproduce it any more. I assume that issue was due to incorrect parameters passed to the getUserMedia. But IE crashed not all the time.

**Comment by jauhenk** [comment]
Guys, IE still crashed sometimes.
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	IEXPLORE.EXE
  Application Version:	11.0.9600.17801
  Application Timestamp:	5536642c
  Fault Module Name:	npTemWebRTCPlugin.dll
  Fault Module Version:	0.8.836.0
  Fault Module Timestamp:	55374d52
  Exception Code:	c0000005
  Exception Offset:	00188030
  OS Version:	6.1.7601.2.1.0.256.4
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

I had a call with audio and video and after I canceled call IE crashed.

**Comment by jauhenk** [comment]
Hey,
Crash was again with the commercial version. I had several calls and after them IE crashed without any activity.
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	IEXPLORE.EXE
  Application Version:	11.0.9600.17801
  Application Timestamp:	5536642c
  Fault Module Name:	npTemWebRTCPlugin.dll
  Fault Module Version:	0.8.843.0
  Fault Module Timestamp:	555d898b
  Exception Code:	c0000005
  Exception Offset:	001a01ae
  OS Version:	6.1.7601.2.1.0.256.4
  Locale ID:	1033
  Additional Information 1:	5684
  Additional Information 2:	568440217a82957059d2ebd164c7fa7c
  Additional Information 3:	5bd3
  Additional Information 4:	5bd3a4cc6734eea49381bda653aea650

**Comment by jauhenk** [comment]
One more crash with the trial commercial version: during audio call I clicked button to start screen sharing, selected screen and got crash.
Problem signature:
  Problem Event Name: APPCRASH
  Application Name: IEXPLORE.EXE
  Application Version: 11.0.9600.17801
  Application Timestamp: 5536642c
  Fault Module Name: npTemWebRTCPlugin.dll
  Fault Module Version: 0.8.843.0
  Fault Module Timestamp: 555d898b
  Exception Code: c0000005
  Exception Offset: 001b9ea4
  OS Version: 6.1.7601.2.1.0.256.4
  Locale ID: 1033
  Additional Information 1: 0a9e
  Additional Information 2: 0a9e372d3b4ad19135b953a78882e789
  Additional Information 3: 0a9e
  Additional Information 4: 0a9e372d3b4ad19135b953a78882e789
