### ISSUE TITLE
getUserMedia works wrong

### ISSUE THREAD

**Issue by jauhenk** [Temasys/AdapterJS#68]
Hey guys,
When I path to the getUserMedia { audio: true, video: false } I still can select video in the popup window. After it I'll be able to get video stream from the stream object in the getUserMedia success callback.
Thanks!

**Comment by johache** [comment]
It was a design choice to let the user override the request made by the website.
Re-reading the specs, I do understand that if the request says no video, the stream MUST not contain a video track.
http://www.w3.org/TR/2015/WD-mediacapture-streams-20150414/#idl-def-MediaStreamConstraints

@agouaillard : what do you think?

**Comment by agouaillard** [comment]
I think the spec is clear.
if the constraint is videoL false, the resulting media stream MUST not have
a video track.
In such case it makes no sense to have a prompt for video at all (you take
the risk to start a video capturer for nothing).

On Thu, Apr 30, 2015 at 10:07 AM, Jacques-Olivier Haché <
notifications@github.com> wrote:

> It was a design choice to let the user override the request made by the
> website.
> Re-reading the specs, I do understand that if the request says no video,
> the stream MUST not contain a video track.
>
> http://www.w3.org/TR/2015/WD-mediacapture-streams-20150414/#idl-def-MediaStreamConstraints
>
> @agouaillard <https://github.com/agouaillard> : what do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Temasys/AdapterJS/issues/68#issuecomment-97634463>.
>



-- 
Alex. Gouaillard, PhD, PhD, MBA
------------------------------------------------------------------------------------
CTO - Temasys Communications, S'pore / Mountain View
President - CoSMo Software, Cambridge, MA
------------------------------------------------------------------------------------
sg.linkedin.com/agouaillard

   -

**Comment by rpastro** [comment]
I agree with @agouaillard. We should not allow the user to overwrite what is being requested by the JS app.

Please note that this should also be applicable for the case where the constraint has audio: false. In this case the user should not be allowed to select a recording device.

**Comment by johache** [comment]
Alright, ticket open in JIRA.

**Comment by jauhenk** [comment]
Hey,
Is it possible to remove video stream manually somehow? When I disable video track sound become disabled also.

**Comment by johache** [comment]
1 - FYI, I implemented the forced respect of the constraints last week. it will be a part of the next release.
2 - Do you mean removing the video track from the stream while keeping the audio track ? MediaStream.removeTrack will also be in the next release.
Did you try getting the video track and setting it to enabled = false ?

**Comment by jauhenk** [comment]
Sounds good!
2 - Yes, but when we will have correct getUserMedia flow - all will be fine

- Did you try getting the video track and setting it to enabled = false ?
- Yes, and sound also became disabled after it.

**Comment by jauhenk** [comment]
Also could you please let me know when next release will be?

**Comment by johache** [comment]
A release including those fixes was done on Aug 13, closing this issue.
https://temasys.atlassian.net/wiki/display/TWPP/WebRTC+Plugins
