### ISSUE TITLE
MediaStreamTrack.getSources() and Firefox

### ISSUE THREAD

**Issue by soulhunter1987** [Temasys/AdapterJS#71]
You have a polyfill for this method in Firefox and it returns two devices - audio and video. I think it would be better to return an empy list here because:
There are three possible alternatives:
1. User has a device, and we know that because getSources() is supported, and it returned that device.
2. User does'not have a device, and we know that because getSources() is supported, but it returned no device.
3. We do not know actually - no getSources() support.
Currently Firefox is the third case, but implemented as the first one. I think that 'unknown' is nearer to 'no' than to 'yes', because 'no' may also be considered as 'unknown' in case user has a device, but it is not plugged in or something like this.
With the current implementation I have to add an extra "if" clause to check for Firefox to get an actually known device list.

**Comment by serrynaimo** [comment]
Not a bad idea. We'll review internally and see what we do.

**Comment by soulhunter1987** [comment]
Maybe it would be also good to send a warning to the console when using this method (whatever it returns), notifying that this method is not really supported and results may be inaccurate.

**Comment by soulhunter1987** [comment]
Hi. Whan about this issue? Currently you have it implemented, but it doesn't work because of a bug (a i think). MediaStreamTrack.getSources() is first defined on line 568 (the wrong definition) and the on line 630 (the correct definition, does not override the first one). I think the only thing you have to do is to remove the first definition and issue wuld be solved :)

**Comment by johache** [comment]
Hi soulhunter,

I agree with you on the 3 cases. 
Given that FF is in the 3rd case, returning yes or no is really an implementation choice.
Our position is to align with Google's version, which is to return audio&video with 'default' ids. 
This is to make ease the swap from one adapter to the other.
Link to Google's adapter: https://github.com/webrtc/samples/blob/master/src/js/adapter.js

I hope this makes our motivation clearer. 
I will close this issue. You can re-open it if you disagree with our choice and have counter arguments to move the other way.

J-O
