### ISSUE TITLE
Take a snapshot

### ISSUE THREAD

**Issue by cumajkeee** [Temasys/AdapterJS#73]
Hi guys,

Are you planing to add some functionality to take a snapshots from camera?
Can't draw image in canvas from object that is returned from plugin.

Thanks in advance.

**Comment by johache** [comment]
Hi,
We have this in the TODO list, but it down in the bottom. 
So it will happen eventually, but not in the close future.
Regards,
J-O

**Comment by Lenne231** [comment]
This would be really useful for us as well!

**Comment by danieldecsi** [comment]
Did you have any process on this?

**Comment by johache** [comment]
Indeed. Closing this ticket.
