### ISSUE TITLE
Calling PeerConnection.removeStream() leads to "undefined is not a function"

### ISSUE THREAD

**Issue by z0r1k** [Temasys/AdapterJS#77]
Hi,

I have a use-case when I need to remove streams from peer connection and by calling ```_pc.removeStream(stream)``` where ```_pc``` is RTCPeerConnection leading to ```undefined is not a function (evaluating '_pc.removeStream(stream)')```.

I checked RTCPeerConnection object and it's prototype and removeStream is defined in prototype but somehow not exposed properly.

Yes, I forgot to mention: I'm running Safari 8.

Is there a workaround for this?

**Comment by johache** [comment]
PC::removeStream is not defined for the plugin at the moment.
You should not even see it declared.
We moved adding removeStream higher in our todo list. It should be done in the next few weeks.

**Comment by johache** [comment]
PC::removeStream was added in the latest releases. 
Closing the ticket.
