### ISSUE TITLE
Both getUserMedia callbacks are called simultaneously 

### ISSUE THREAD

**Issue by z0r1k** [Temasys/AdapterJS#78]
When camera is already in use (by another getUserMedia call) and next getUserMedia call prompts device selection dialog and same camera is selected (which works fine for native implementation) both success and failure callbacks are called.

Error callback gets error object containing message that constraints are not fulfilled. 
Success callback gets stream object which is valid but contains no audio/video stream tracks (depends on initial constraints).

This behaviour is wrong since only one callback should be called and in this case - error callback.

Thanks.

**Comment by yurytarasevich** [comment]
Hello guys,

I have the same problem.

When I already have a video stream on the page and try to call `getUserMedia()` I receive two callbacks simultaneously (from second call).

Something like this:

- code:
```javascript
TemasysAdapter.getUserMedia({audio: true, video: true}, function (stream) {
    console.log("1 - OK", stream);    
}, function (error) {
    console.log("1 - ERROR", error);
});

window.setTimeout(function () {
    TemasysAdapter.getUserMedia({audio: true, video: true}, function (stream) {
        console.log("2 - OK", stream);    
    }, function (error) {
        console.log("2 - ERROR", error);
    });
}, 1000);
```

- console:
```javascript
getUserMedia [object Object]
getUserMedia [object Object]
1 - OK <JSAPI-Auto Javascript Object>
2 - ERROR [object Object]
2 - OK <JSAPI-Auto Javascript Object>
```

Thank you.

**Comment by johache** [comment]
Hey guys,

Yes, this is a know issue that popped in 0.8.836 when we did a large refactoring of GUM. Our testing didn't catch it...
We already have a fix internally, it will be part of the next release.

Thank you
