### ISSUE TITLE
browserify version doesnt actually export anything

### ISSUE THREAD

**Issue by contra** [Temasys/AdapterJS#81]
the AdapterJS object is created but never exported via module.exports

**Comment by serrynaimo** [comment]
Hey @contra,

yeah, we were not putting it in to not give the impression that you should use it that way. AdapterJS shims and polyfills and needs to be available on the global namespace.

I'll keep this ticket open tho and maybe we aggregate a few more opinions.

**Comment by contra** [comment]
@serrynaimo I think everyone understands how the shim puts stuff on the window, but the library also exposes other stuff that is totally lost when using browserify. This is how it seems like it would work:

```js
var adapter = require('adapterjs');

adapter.onwebrtcready = function(usingPlugin){
  adapter.attachMediaStream(whatever, whatever);
};
```

**Comment by serrynaimo** [comment]
It's still available via the AdapterJS global variable, but I get what you mean. I can't see any harm of putting an export in. Will discuss internally. Thanks!

**Comment by contra** [comment]
@serrynaimo Actually no, there is no AdapterJS global created using browserify so this is unusable with browserify currently

**Comment by serrynaimo** [comment]
@contra Try the 0.11.0 version.

**Comment by contra** [comment]
None of the helper functions are exported in the adapterjs object
