### ISSUE TITLE
Support promise based API

### ISSUE THREAD

**Issue by z0r1k** [Temasys/AdapterJS#88]
Are there any plans to support promises for WebRTC? https://w3c.github.io/webrtc-pc/#interface-definition

**Comment by serrynaimo** [comment]
Not as of now.

**Comment by z0r1k** [comment]
Would be very nice of you if you could share roadmap for plugin somewhere.
Because if official spec is promise based and FF supports both promise and "legacy" way and Chrome is slowly adding support for promise based APIs there is clear trend that "legacy" APIs will be dropped eventually.
I think if plugin wants to be specs compatible it will have to catch up eventually.
