### ISSUE TITLE
IE crash when new plugin version is available

### ISSUE THREAD

**Issue by jauhenk** [Temasys/AdapterJS#94]
Dear Temasys,
I found that when new plugin version is available - IE crashes sometimes. It happens before notification bar appears during initialization of an application.
Could you please take a look?

**Comment by johache** [comment]
Hi,
We saw this issue and already released a fix in 0.8.850.
I posted an announce here: https://groups.google.com/forum/#!topic/temasys-discuss-webrtcplugin/lEEFzhr_1e0
When the next version is out, this crash should not appear.

Thanks for the feedback though ;)
