### ISSUE TITLE
MediaStream should have real stream id in ID property

### ISSUE THREAD

**Issue by z0r1k** [Temasys/AdapterJS#95]
Hi,

currently Chrome and Firefox are having real meaningful stream id in both MediaStream.id and MediaStream.label.
Temasys plugin has it in label only and id contain some custom string value which is not useful since it doesn't represent stream id.

In Chrome Canary 46 I started to get a warning like this:
```'MediaStream.label' is deprecated and will be removed in M47, around November 2015. Please use 'MediaStream.id' instead.```

So since temasys plugin is based on spec it should use id instead of label.

Thanks.

**Comment by johache** [comment]
The plugin has been supporting both id and label for a while, 
I think this issue should have been closed a long time ago. 
Closing now, feel free to re-open should you think it is relevant
