### ISSUE TITLE
Statistics reporting only 1 track 

### ISSUE THREAD

**Issue by marcinag** [Temasys/AdapterJS#97]
Hi,

My question is also related to issue #62. 

I played a bit with the statistics and it seems to me that I can only see the statistics from the received video track. In my application, I'm running a p2p session between 2 users.

Here is the stat object we get:
```json
{ Timestamp: "1438100065133.217"
bytesReceived: "1565969"
googCaptureStartNtpTimeMs: "3647088844748"
googCurrentDelayMs: "72"
googDecodeMs: "2"
googFirsSent: "0"
googFrameHeightReceived: "480"
googFrameRateDecoded: "0"
googFrameRateOutput: "0"
googFrameRateReceived: "31"
googFrameWidthReceived: "640"
googJitterBufferMs: "50"
googMaxDecodeMs: "12"
googMinPlayoutDelayMs: "0"
googNacksSent: "0"
googPlisSent: "0"
googRenderDelayMs: "10"
googTargetDelayMs: "72"
googTrackId: "e1a561fe-798e-4204-96cb-62c3d0958db2"
packetsLost: "0"
packetsReceived: "1645"
ssrc: "2988131868"
transportId: "Channel-audio-1"
type: "ssrc" }
```

Thanks for help.

**Comment by marcinag** [comment]
In our call we have two users: 7280 (using Chrome) and 3845 (using Safari)
![screen shot 2015-07-29 at 09 54 12](https://cloud.githubusercontent.com/assets/1918281/8951613/ccb2d0ac-35d7-11e5-8877-569105eff7e8.png)

But we collect stats only for incoming video in Safari. So in the screenshot below latency (reported in outgoing track) is reported only by the Chrome user.

![screen shot 2015-07-29 at 09 53 32](https://cloud.githubusercontent.com/assets/1918281/8951604/c0589db4-35d7-11e5-8c37-9f3b80c69500.png)

**Comment by vr000m** [comment]
any updates on this? are we doing something incorrectly, pointers are appreciated.

**Comment by johache** [comment]
I believe your implementation is correct. 
It is possible the plugin offers less information that Chrome would. I don't know what Firefox offers, can someone enlighten me on this?

**Comment by agouaillard** [comment]
mozilla.dev.media is a mailing list I suggested all tech employees at
temasys follow. It's listed in confluence.

Two days ago you had this enlightening email:
https://groups.google.com/d/msg/mozilla.dev.media/XW2UPHEUo8Y/fz8-MUuOCwAJ

which eventually point to:
http://stackoverflow.com/questions/29800010/can-someone-comprehensively-explain-the-webrtc-stats-api/29840886#29840886

Hope this helps.

Alex.

On Thu, Aug 13, 2015 at 10:54 AM, Jacques-Olivier Haché <
notifications@github.com> wrote:

> I believe your implementation is correct.
> It is possible the plugin offers less information that Chrome would. I
> don't know what Firefox offers, can someone enlighten me on this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Temasys/AdapterJS/issues/97#issuecomment-130512617>.
>



-- 
Alex. Gouaillard, PhD, PhD, MBA
------------------------------------------------------------------------------------
CTO - Temasys Communications, S'pore / Mountain View
President - CoSMo Software, Cambridge, MA
------------------------------------------------------------------------------------
sg.linkedin.com/agouaillard

   -

**Comment by vr000m** [comment]
Thanks @agouaillard and @johache. Since the plugin is based on chrome's codebase, we were hoping this would just work. Is there an estimate when the plugin would mirror the chrome stats?

Hmmm... It should be noted though that chrome does not return the format as specified in webrttc-stats. But that is not the problem as we have enough experience adapting what chrome returns to what the webrtc-stats describes.

**Comment by agouaillard** [comment]
I let jo answer for temasys.

you are right, getstats returns instantaneous stats, while webrtc-internals
sample along the life of a peer connection, and also returns extra
parameters. Same for about::webrtc in firefox.

Note that the specs is far from being defined on getstats and it's changing
every two weeks in both chrome and firefox codebase. It makes it difficult
to decide what to use and what not too, even without putting the plugin in
the picture.

Alex.

On Thu, Aug 13, 2015 at 7:38 PM, Varun Singh <notifications@github.com>
wrote:

> Thanks @agouaillard <https://github.com/agouaillard> and @johache
> <https://github.com/johache>. Since the plugin is based on chrome's
> codebase, we were hoping this would just work. Is there an estimate when
> the plugin would mirror the chrome stats?
>
> Hmmm... It should be noted though that chrome does not return the format
> as specified in webrttc-stats. But that is not the problem as we have
> enough experience adapting what chrome returns to what the webrtc-stats
> describes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Temasys/AdapterJS/issues/97#issuecomment-130631518>.
>



-- 
Alex. Gouaillard, PhD, PhD, MBA
------------------------------------------------------------------------------------
CTO - Temasys Communications, S'pore / Mountain View
President - CoSMo Software, Cambridge, MA
------------------------------------------------------------------------------------
sg.linkedin.com/agouaillard

   -

**Comment by vr000m** [comment]
I suppose this issue is closed: http://www.callstats.io/2016/02/01/temasys-plugin-integration/ :) thanks for getting it done.

**Comment by johache** [comment]
Awesome, thanks for taking the time to update callstats.io !
I'm closing this issue :)
